gfc_7.prototype.safeSlice=gfc_b(20,function(a,b,c){return a?c<b?[]:a.slice(Math.min(b,a.length),Math.min(c,a.length)):[]});gfc_7.prototype.share=gfc_b(18,function(){gfc_Yh();return!1});gfc_7.prototype.popGoBack=gfc_b(16,function(){return this.goBackStack_.pop()});gfc_7.prototype.unwindGoBackStack=gfc_b(15,function(){var a=this.baseState_;a.valid?(this.state_=this.copyState_(this.baseState_),this.jstProcessView_(a.view)):(this.baseState_=null,this.render(a.actions,a.view,a.params));this.clearGoBackStack()});
gfc_v.prototype.ceil=gfc_b(3,function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this});gfc_Ub.prototype.ceil=gfc_b(2,function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this});gfc_4c.prototype.ceil=gfc_b(1,function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this});
gfc_M.prototype.ceil=gfc_b(0,function(){this.left=Math.ceil(this.left);this.top=Math.ceil(this.top);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this});
var gfc_ji=function(a){return a=window.friendconnect_serverBase+"/friendconnect/favicon?url="+escape(a)},gfc_li=function(a,b,c){this.initMsgs();this.initBloggerMsgs();var d=new gfc_K;d.set("members",{action:this.requestMembers_,callback:this.processMembers_});d.set("member-page",{action:this.requestMembersPage_,callback:this.processMembersPage_});d.set("blocked-member-page",{action:this.requestBlockedMembersPage_,callback:this.processBlockedMembersPage_});d.set("profile-friends-page",{action:this.requestProfileFriendsPage_,
callback:this.processProfileFriendsPage_});d.set("sitesData",{action:this.requestSitesData_,callback:this.processSitesData_});d.set("viewerFriends",{action:this.requestViewerFriends_,callback:this.processViewerFriends_});d.set("profileData",{action:this.requestProfileData_,callback:this.processProfileData_});d.set("blockUser",{action:this.requestBlockUser_,callback:this.processBlockUser_});d.set("unblockUser",{action:this.requestUnblockUser_,callback:this.processUnblockUser_});d.set("profileFriends",
{action:this.requestProfileFriends_,callback:this.processProfileFriends_});d.set("activityData",{action:this.requestActivityData_,callback:this.processActivityData_});d.set("sendFriendRequest",{action:this.requestSendFriendRequest_,callback:this.processSendFriendRequest_});d.set("sendFriendRequestResponse",{action:this.requestFriendRequestResponse_,callback:this.processFriendRequestResponse_});d.set("deleteActivity",{action:this.requestDeleteActivity_,callback:this.processActivityData_});d.set("requestAndProcessViewerNumWaitingMessages",
{action:this.requestViewerNumWaitingMessages_,callback:this.processViewerNumWaitingMessages_});d.set("requestPromo",{action:this.requestPromo_,callback:this.processPromo_});this.siteSettings_=null;this.optionsMenuWrapper_=new gfc_5h("fc-members-options-menu",gfc_k(this.optionsMenuButtonBuilder,this),gfc_k(this.optionsMenuBoxBuilder,this),gfc_k(this.optionsMenuHandler_,this),0,window.friendconnect_serverBase,this.getSkinProperty("ENDCAP_LINK_COLOR")||"0000cc",this.getSkinProperty("CONTENT_TEXT_COLOR")||
"000000");this.showInvitedBy_=!1;this.activityPageSize_=10;this.linksPageSize_=15;this.sitesPageSize_=10;var e=gfc_P(gfc_cd()),f=gfc_ki;this.facesPerRow_=3;this.facesRows_=8;this.scrollHeight_=null;this.maxFacesPerPage_=this.facesRows_*this.facesPerRow_;this.slimTopCapHeight=19;this.tinyTopCapHeight=8;this.isMessagingEnabled=a;this.isPromosEnabled=b;this.isSocialShareEnabled=c;this.numWaitingMessages=0;this.promoCode=-1;this.promoHtml=null;this.util_=new gfc_1h;this.isProfileMode()&&(a=(a=this.getSkinProperty(f.FACE_SIZE))?
Number(a):32,a+=6,this.facesPerRow_=Math.floor((e.width-10)/a),e=340,e=this.getSkinProperty(f.HEIGHT),b=this.getSkinProperty(f.NUMBER_ROWS),f=27,b?(this.facesRows_=Number(b),e=this.facesRows_*a,this.scrollHeight_=e+f):e&&(e=Number(e)-96,this.facesRows_=Math.max(2,Math.floor(e/a)),this.scrollHeight_=this.facesRows_*a+f),this.maxFacesPerPage_=this.facesRows_*this.facesPerRow_);gfc_7.call(this,d)};gfc_m(gfc_li,gfc_7);gfc_=gfc_li.prototype;
gfc_.start=function(){gfc_li.superClass_.start.call(this);gfc_5("start");var a=gadgets.views.getParams(),b=_args();(a=b.profileId||a.profileId)?(b={},b[opensocial.Person.Field.ID]=a,a=new opensocial.Person(b),this.render(["profileData","profileFriends","activityData"],"profile",{person:a})):(a=["members","viewerFriends"],this.isMessagingEnabled&&a.push("requestAndProcessViewerNumWaitingMessages"),this.isPromosEnabled&&!this.isCanvasMode()&&a.push("requestPromo"),this.render(a,"faces"))};
gfc_.defaultThemeMsgs_={};
gfc_.initMsgs=function(){this.defaultThemeMsgs_.MSG_SITE_MEMBERS="Members";this.defaultThemeMsgs_.MSG_BE_THE_FIRST="Be the first!";this.defaultThemeMsgs_.MSG_NO_SITE_MEMBERS="There are no members yet.";this.defaultThemeMsgs_.MSG_ALL_SITE_MEMBERS="All Members";this.defaultThemeMsgs_.MSG_ALL_BLOCKED_MEMBERS="All Blocked Members";this.defaultThemeMsgs_.MSG_NO_BLOCKED_MEMBERS="You have not blocked any members";this.defaultThemeMsgs_.MSG_YOUR_FRIENDS="Your Friends";this.defaultThemeMsgs_.MSG_ALL_YOUR_FRIENDS="All Your Friends";
this.defaultThemeMsgs_.MSG_JFJ="Join and connect with others!";this.defaultThemeMsgs_.MSG_MANAGE="Manage members";this.defaultThemeMsgs_.MSG_SETTINGS="Settings";this.defaultThemeMsgs_.MSG_OPTIONS="Options";this.defaultThemeMsgs_.MSG_MEMBERS_SHARE="Share this page";this.defaultThemeMsgs_.MSG_BACK="Back";this.defaultThemeMsgs_.MSG_BACK_TO_TOP="Home";this.defaultThemeMsgs_.MSG_VIEW_MY_PROFILE="View my profile";this.defaultThemeMsgs_.MSG_ABOUT_ME="About me";this.defaultThemeMsgs_.MSG_MORE="More \u00bb";
this.defaultThemeMsgs_.MSG_SHOW_BLOCKED="Show blocked members \u00bb";this.defaultThemeMsgs_.MSG_SHOW_ALL="\u00ab Show all members";this.defaultThemeMsgs_.MSG_LINK_IN_NETWORKS="Link in your social networks";this.defaultThemeMsgs_.MSG_ACTIVITIES="Activities";this.defaultThemeMsgs_.MSG_ALL_ACTIVITIES="More activities";this.defaultThemeMsgs_.MSG_DELETE_THIS="Delete";this.defaultThemeMsgs_.MSG_SITES="Sites I've joined";this.defaultThemeMsgs_.MSG_ALL_SITES="More sites I've joined";this.defaultThemeMsgs_.MSG_LINKS=
"Links";this.defaultThemeMsgs_.MSG_ALL_LINKS="More links";this.defaultThemeMsgs_.MSG_NO_ACTIVITIES="No activities to show";this.defaultThemeMsgs_.MSG_ADD_AS_FRIEND="Add as friend";this.defaultThemeMsgs_.MSG_SEND_MESSAGE="Send a message";this.defaultThemeMsgs_.MSG_BLOCK_USER="Block this user";this.defaultThemeMsgs_.MSG_UNBLOCK_USER="Unblock this user";this.defaultThemeMsgs_.MSG_USER_IS_ADMIN="Administrator";this.defaultThemeMsgs_.MSG_JOIN="Join this site";this.defaultThemeMsgs_.MSG_OR="or";this.defaultThemeMsgs_.MSG_SIGN_IN=
"Sign in";this.defaultThemeMsgs_.MSG_SIGN_OUT="Sign out";this.defaultThemeMsgs_.MSG_PREVIOUS="\u00ab Previous";this.defaultThemeMsgs_.MSG_NEXT="Next \u00bb";this.defaultThemeMsgs_.MSG_NEWER="\u00ab Newer";this.defaultThemeMsgs_.MSG_OLDER="Older \u00bb";this.defaultThemeMsgs_.MSG_ACCEPT_ALL_FRIEND_REQUESTS="Accept all";this.defaultThemeMsgs_.MSG_HELP_FRIENDREQUEST="You and your friends will see each other across all Friend Connect sites.";this.defaultThemeMsgs_.MSG_HELP_FRIENDINVITE="Once you are friends, you will see each other across all Friend Connect sites.";
this.defaultThemeMsgs_.MSG_HELP_BLOCKMEMBER="Blocking a visitor removes them from the members list and prevents them from interacting with other visitors on your site";this.defaultThemeMsgs_.MSG_INVITATION="Invitation:";this.defaultThemeMsgs_.MSG_SEND="Send";this.defaultThemeMsgs_.MSG_BLOCK="Block";this.defaultThemeMsgs_.MSG_IGNORE="Ignore";this.defaultThemeMsgs_.MSG_CANCEL="Cancel";this.defaultThemeMsgs_.MSG_SITE_SETTINGS="Site settings";this.defaultThemeMsgs_.MSG_ABOUT_FC="About Friend Connect";
this.defaultThemeMsgs_.MSG_ALREADY_MEMBER="Already a member?";this.defaultThemeMsgs_.MSG_EDIT_PROFILE="Edit profile"};gfc_.bloggerThemeMsgs_={};
gfc_.initBloggerMsgs=function(){this.bloggerThemeMsgs_.MSG_SITE_MEMBERS="Followers";this.bloggerThemeMsgs_.MSG_NO_SITE_MEMBERS="There are no followers yet.";this.bloggerThemeMsgs_.MSG_SHOW_BLOCKED="Show blocked followers \u00bb";this.bloggerThemeMsgs_.MSG_SHOW_ALL="\u00ab Show all followers";this.bloggerThemeMsgs_.MSG_ALL_SITE_MEMBERS="All Followers";this.bloggerThemeMsgs_.MSG_ALL_BLOCKED_MEMBERS="All Blocked Followers";this.bloggerThemeMsgs_.MSG_NO_BLOCKED_MEMBERS="You have not blocked any followers";
this.bloggerThemeMsgs_.MSG_LIKE_THIS_SITE="Like this blog?";this.bloggerThemeMsgs_.MSG_JOIN="Follow";this.bloggerThemeMsgs_.MSG_BACK_TO_TOP="Members";this.bloggerThemeMsgs_.MSG_JFJ="Follow and connect with your friends!";this.bloggerThemeMsgs_.MSG_HELP_FRIENDREQUEST="You and your friends will see each other across all Following blogs and Friend Connect sites.";this.bloggerThemeMsgs_.MSG_HELP_FRIENDINVITE="Once you are friends, you will see each other across all Following blogs and Friend Connect sites."};
gfc_.prepareContext=function(a,b){var c=!0;if(b.profile&&b.profile.person){var d={},e=b.profile.person.getDisplayName()+" is your friend";d.MSG_IS_FRIEND=e;e="You have invited "+(b.profile.person.getDisplayName()+" to be your friend");d.MSG_IS_INVITED=e;e=b.profile.person.getDisplayName()+"'s friends";d.MSG_PROFILE_FRIENDS=e;e="All "+(b.profile.person.getDisplayName()+"'s friends");d.MSG_ALL_PROFILE_FRIENDS=e;for(var f in d)this.addToContext(a,f,d[f])}b.invitedBy&&b.invitedBy.getDisplayName()&&(d=
document.width?document.width:document.body.clientWidth+2,c=(d-135)/8,d=(d-175)/8,c="View "+(gfc_th(b.invitedBy.getDisplayName(),c)+"'s profile"),d=gfc_th(b.invitedBy.getDisplayName(),d)+" invited you to this site",this.addToContext(a,"MSG_VIEW_INVITER_PROFILE",c),this.addToContext(a,"MSG_INVITED_YOU",d),this.showInvitedBy_=!0,c=!1);d=this.numWaitingMessages+" messages waiting for you.";this.isMessagingEnabled&&0<this.numWaitingMessages&&(c=!1,this.addToContext(a,"showWaitingMessages",!0),this.isMessagingEnabled&&
(this.addToContext(a,"MSG_NUM_WAITING_MESSAGES",d),this.addToContext(a,"MSG_VIEW_AND_CONFIGURE_MESSAGING","View messages")));b.friendRequests&&(0<b.friendRequests.size()&&(c=!1),d=1==b.friendRequests.size()?"New friend request \u00bb":"New friend requests ("+(b.friendRequests.size()+") \u00bb"),this.addToContext(a,"MSG_NEW_FRIEND_REQUESTS",d));if(this.siteSettings_){if(this.isBloggerTheme_(this.siteSettings_.themeId))for(f in this.bloggerThemeMsgs_)this.addToContext(a,f,this.bloggerThemeMsgs_[f]);
this.siteSettings_.signInPrompt&&this.addToContext(a,"MSG_JOIN",this.siteSettings_.signInPrompt);this.siteSettings_.signOutPrompt&&this.addToContext(a,"MSG_SIGN_OUT",this.siteSettings_.signOutPrompt)}this.addToContext(a,"isViewerAdmin",b.isViewerAdmin);this.addToContext(a,"isMessagingEnabled",this.isMessagingEnabled);this.addToContext(a,"acceptMessages",this.acceptMessages);this.addToContext(a,"isViewingSelf",b.viewer&&b.profile&&b.profile.person&&b.viewer.getId()==b.profile.person.getId());d=!1;
if(b.owner&&(e=b.owner.getField("profileExtensions")))for(f in e)d=!0;this.addToContext(a,"communityHasProfile",d);this.addToContext(a,"promoHtml",c?this.promoHtml:null);this.addToContext(a,"insertHtml",function(a,b){a.innerHTML=b})};gfc_.isBloggerTheme_=function(a){return"blogger"==a};gfc_.generateSignInButton_=function(a,b,c,d){gfc_Wh({id:a,text:b,version:this.isBloggerTheme_(this.siteSettings_.themeId)?1:null,style:c},d)};
gfc_.initBaseContext=function(a){function b(b,c){d.addToContext(a,b,gfc_k(c,d))}this.addToContext(a,"facesPerRow",this.facesPerRow_);for(var c in this.defaultThemeMsgs_)this.addToContext(a,c,this.defaultThemeMsgs_[c]);var d=this;b("getThumbnail",this.getThumbnail);b("map",this.map);b("elide",gfc_th);b("safeSlice",this.safeSlice);b("showAllActivities",this.showAllActivities_);b("transformActivity",this.transformActivity_);b("nextActivities",this.nextActivities_);b("previousActivities",this.previousActivities_);
b("showAllLinks",this.showAllLinks_);b("transformLink",this.transformLink_);b("nextLinks",this.nextLinks_);b("previousLinks",this.previousLinks_);b("showAllSites",this.showAllSites_);b("transformSite",this.transformSite_);b("nextSites",this.nextSites_);b("previousSites",this.previousSites_);b("showAllMembers",this.showAllMembers_);b("showBlockedMembers",this.showBlockedMembers_);b("showUnblockedMembers",this.showUnblockedMembers_);b("nextMembers",this.nextMembers_);b("nextBlockedMembers",this.nextBlockedMembers_);
b("previousMembers",this.previousMembers_);b("previousBlockedMembers",this.previousBlockedMembers_);b("showAllProfileFriends",this.showAllProfileFriends_);b("nextProfileFriends",this.nextProfileFriends_);b("previousProfileFriends",this.previousProfileFriends_);b("showAllViewerFriends",this.showAllViewerFriends_);b("nextViewerFriends",this.nextViewerFriends_);b("previousViewerFriends",this.previousViewerFriends_);b("isHome",this.isHome);b("goBack",this.goBack);b("goBackToHome",this.showMembersCollection_);
b("editSettings",this.editSettings);b("signout",this.signout);b("signin",this.signin);b("viewProfile",this.viewProfile_);b("blockUser",this.blockUser_);b("unblockUser",this.unblockUser_);b("goToInviteFriend",this.goToInviteFriend_);b("sendMessageDialog",this.sendMessageDialogWrapper_);b("goToBlockMember",this.goToBlockMember_);b("goToEditProfile",this.editSettings);b("goToViewerProfile",this.goToViewerProfile_);b("sendInvite",this.sendInvite_);b("blockMember",this.blockMember_);b("acceptFriendRequest",
this.acceptFriendRequest_);b("ignoreFriendRequest",this.ignoreFriendRequest_);b("viewFriendRequests",this.viewFriendRequests_);b("acceptAllFriendRequests",this.acceptAllFriendRequests_);b("numPreviewFriends",this.getNumPreviewFriends_);b("numPreviewMembers",this.getNumPreviewMembers_);b("showInvitedBy",this.getShowInvitedBy_)};
gfc_.getNumPreviewFaces_=function(a){a=Math.max(1,a?this.facesRows_-1:this.facesRows_);var b=this.state_.data.members?this.state_.data.members.size():0,c=this.state_.data.friends?this.state_.data.friends.size():0,b=Math.ceil(b/this.facesPerRow_),c=Math.ceil(c/this.facesPerRow_);b>Math.ceil(a/2)?c>Math.floor(a/2)?(b=Math.ceil(a/2),c=Math.floor(a/2)):b=Math.max(0,a-c):c>Math.floor(a/2)&&(c=Math.max(0,a-b));b*=this.facesPerRow_;c*=this.facesPerRow_;return a={numMembers:b,numFriends:c}};
gfc_.getNumPreviewMembers_=function(a){return this.getNumPreviewFaces_(a).numMembers};gfc_.getNumPreviewFriends_=function(a){return this.getNumPreviewFaces_(a).numFriends};
gfc_.requestMembersPage_=function(a,b){var c=opensocial.newDataRequest(),d={},e=opensocial.DataRequest.PeopleRequestFields;d[e.FILTER]="PUBLICLY_VISIBLE";d[e.FIRST]=b.start;d[e.MAX]=b.pageSize?b.pageSize:this.maxFacesPerPage_;var f=[opensocial.Person.Field.ID,opensocial.Person.Field.NAME,opensocial.Person.Field.THUMBNAIL_URL];d[e.PROFILE_DETAILS]=f;d[opensocial.DataRequest.DataRequestFields.ESCAPE_TYPE]=opensocial.EscapeType.NONE;c.add(c.newFetchPeopleRequest(gfc_Ya(),d),"ownerFriends");c.send(a)};
gfc_.processMembersPage_=function(a){this.state_.data.members=a.get("ownerFriends").getData()};
gfc_.requestBlockedMembersPage_=function(a,b){var c=opensocial.newDataRequest(),d={},e=opensocial.DataRequest.PeopleRequestFields;d[e.FIRST]=b.start;d[e.MAX]=b.pageSize?b.pageSize:this.maxFacesPerPage_;d[opensocial.DataRequest.DataRequestFields.ESCAPE_TYPE]=opensocial.EscapeType.NONE;e={};e[opensocial.IdSpec.Field.USER_ID]=opensocial.IdSpec.PersonId.OWNER;e[opensocial.IdSpec.Field.GROUP_ID]="BLOCKED";e[opensocial.IdSpec.Field.NETWORK_DISTANCE]=1;e=opensocial.newIdSpec(e);c.add(c.newFetchPeopleRequest(e,
d),"blockedMembers");c.send(a)};gfc_.processBlockedMembersPage_=function(a){this.state_.data.blockedMembers=a.get("blockedMembers").getData()};
gfc_.requestProfileFriendsPage_=function(a,b){var c=opensocial.newDataRequest(),d=b&&b.person&&b.person.getId()||this.data_.profile.person.getId(),e={},f=opensocial.DataRequest.PeopleRequestFields;e[f.FIRST]=b.start;e[f.MAX]=b.pageSize?b.pageSize:this.maxFacesPerPage_;d=this.newFriendsIdSpec(d);e[opensocial.DataRequest.DataRequestFields.ESCAPE_TYPE]=opensocial.EscapeType.NONE;c.add(c.newFetchPeopleRequest(d,e),"profileFriends");c.send(a)};
gfc_.newFriendsIdSpec=function(a){var b={};b[opensocial.IdSpec.Field.USER_ID]=a;b[opensocial.IdSpec.Field.GROUP_ID]="FRIENDS";b[opensocial.IdSpec.Field.NETWORK_DISTANCE]=1;return opensocial.newIdSpec(b)};gfc_.processProfileFriendsPage_=function(a){this.state_.data.profile.friends=a.get("profileFriends").getData()};gfc_.allRequestsAreLoaded_=function(a){for(var b=opensocial.data.getDataContext(),c=0;c<a.length;c++){var d=a[c],d=b.getDataSet(d);if(!d||d.code)return!1}return!0};
gfc_.requestMembers_=function(a){var b=this.maxFacesPerPage_,c=!b||24==b;c&&opensocial.data&&this.allRequestsAreLoaded_(["ownerFriends","viewer","siteSettings","friendRequests"])?a(opensocial.data.getDataContext().getData()):(c=osapi.newBatch(),b={userId:"@owner",groupId:"@friends",count:b,filterBy:"PUBLICLY_VISIBLE"},c.add("ownerFriends",osapi.people.get(b)),c.add("viewer",osapi.people.getViewer()),c.add("siteSettings",osapi.extensions.get({command:"GetSiteSettings"})),c.add("friendRequests",osapi.extensions.get({command:"GetFriendRequests",
params:'{"idSpec" : "VIEWER"}'})),(b=_args().psinvite)&&c.add("invitedBy",osapi.extensions.get({command:"DecodeInvitation",params:{token:b}})),c.execute(a))};
gfc_.processMembers_=function(a,b){this.state_.data.members=gfc_Qa(a.ownerFriends,gfc_La);this.state_.data.viewer=gfc_La(a.viewer);this.processFriendRequestResponse_(a,b,!0);this.siteSettings_=a.siteSettings;var c=_args();!c.psinvite||null!=this.state_.data.viewer&&""!=this.state_.data.viewer||(a.invitedBy&&(a.invitedBy.nickname=a.invitedBy.displayName),this.state_.data.invitedBy=new opensocial.Person(a.invitedBy))};
gfc_.requestViewerFriends_=function(a,b){b=b||{};var c=b.pageSize||this.maxFacesPerPage,d=!b.start||0==b.start,e=!c||20==c;d&&e&&opensocial.data&&this.allRequestsAreLoaded_(["friends","isViewerAdmin"])?a(opensocial.data.getDataContext().getData()):(d=osapi.newBatch(),c={userId:"@viewer",groupId:"@friends",count:c},b.start&&(c.startIndex=b.start),d.add("friends",osapi.people.get(c)),d.add("isViewerAdmin",osapi.people.get({userId:"@viewer",groupId:"ADMINS"})),d.execute(a))};
gfc_.processViewerFriends_=function(a){var b=a.friends;b&&!b.error&&(this.state_.data.friends=gfc_Qa(b,gfc_La));this.setAdminHelper_(a)};gfc_.requestViewerNumWaitingMessages_=function(a){var b=opensocial.newDataRequest();b.add(gfc_Oa("VIEWER"),"numWaitingMessages");b.send(a)};gfc_.processViewerNumWaitingMessages_=function(a){this.numWaitingMessages=a.get("numWaitingMessages").getData().numberOfWaitingMessages};
gfc_.requestPromo_=function(a){this.log("requesting promo");var b=new gadgets.Prefs,b=b.getLang()+(b.getCountry()?"_"+b.getCountry():""),c=opensocial.newDataRequest();c.add(gfc_n("GetPromo",{hl:b}),"promo");c.send(a)};gfc_.processPromo_=function(a){this.log("processing promo");(a=a.get("promo").getData())&&-1!=a.promoCode&&(this.promoCode=a.promoCode,this.promoHtml=a.promoHtml)};
gfc_.addPromoDismissHandler=function(){for(var a=function(){this.promoHtml=null;for(var a=gfc_F("div","fc-promo-main",gfc_E("peg")),b=0;b<a.length;b++)gfc_Q(a[b],!1);this.renderDone();this.log("Dismissing promo "+this.promoCode);a=opensocial.newDataRequest();a.add(gfc_n("DismissPromo",{promoCode:this.promoCode}));a.send(gfc_k(function(){this.log("The promo has been dismissed");this.promoCode=-1},this))},b=gfc_F("a","fc-promo-dismiss-link",gfc_E("peg")),c=0;c<b.length;c++){var d=b[c],e="click";gfc_6d(d,
e);gfc_V(d,e,gfc_k(a,this))}};gfc_.setAdminHelper_=function(a){var b=a.isViewerAdmin;b&&!b.error?this.state_.data.isViewerAdmin=b.list.length:a.get&&a.get("isViewerAdmin")&&(a=a.get("isViewerAdmin"))&&!a.hadError()&&(this.state_.data.isViewerAdmin=a.getData().size())};
gfc_.acceptAllFriendRequests_=function(a){var b=[];a.each(function(a){a={user:a.getField(goog.opensocial.peoplesense.Invite.Field.INVITER).getId(),action:"ACCEPT"};b.push(a)});this.render(["sendFriendRequestResponse","members","viewerFriends"],gfc_k(this.chooseViewAfterFriendRequest_,this),{friendRequestResponses:b})};gfc_.showMembersCollection_=function(){this.pushGoBack();this.render(["members","viewerFriends"],"faces")};
gfc_.acceptFriendRequest_=function(a){a={user:a.getId(),action:"ACCEPT"};this.render(["sendFriendRequestResponse","members","viewerFriends"],gfc_k(this.chooseViewAfterFriendRequest_,this),{friendRequestResponses:[a]})};gfc_.viewFriendRequests_=function(){this.pushGoBack();this.invokeView("friend-requests")};gfc_.viewProfile_=function(a){this.isCanvasMode()?(this.pushGoBack(),this.viewProfileNoStack_(a)):gfc_Ba(a.getId())};
gfc_.viewProfileNoStack_=function(a){this.render(["profileData","profileFriends","activityData"],"profile",{person:a})};gfc_.requestSitesData_=function(a,b){var c=opensocial.newDataRequest(),d=opensocial.DataRequest.PeopleRequestFields,e={};e[d.FIRST]=b&&b.start?b.start:0;var f=this.state_.data.profile.person.getId();e[d.MAX]=this.sitesPageSize_;c.add(gfc_Va(opensocial.newIdSpec({userId:f}),e),"profileSites");c.send(a)};gfc_.processSitesData_=function(a){this.state_.data.profile.sites=a.get("profileSites").getData()};
gfc_.requestProfileData_=function(a,b){this.state_.data.profile={};b=b||{};var c=b.person,d={},c=c.getId(),e=opensocial.newDataRequest(),f=[opensocial.Person.Field.ID,opensocial.Person.Field.NAME,opensocial.Person.Field.THUMBNAIL_URL,opensocial.Person.Field.ABOUT_ME,opensocial.Person.Field.URLS,"profileExtensions"],g=opensocial.DataRequest.PeopleRequestFields;d[g.PROFILE_DETAILS]=f;d[opensocial.DataRequest.DataRequestFields.ESCAPE_TYPE]=opensocial.EscapeType.NONE;e.add(e.newFetchPersonRequest(c,d),
"profile");e.add(e.newFetchPersonRequest("VIEWER",d),"viewer");e.add(gfc_Ta("VIEWER","ADMINS"),"isViewerAdmin");e.add(e.newFetchPersonRequest("OWNER",d),"owner");this.siteSettings_||e.add(gfc_Na(),"siteSettings");e.add(gfc_Ta(c,"ADMINS"),"isAdmin");e.add(gfc_Ta(c,"BLOCKED"),"isBlocked");this.isMessagingEnabled&&e.add(gfc_Oa(c),"canMessage");e.send(a)};
gfc_.requestActivityData_=function(a,b){var c=b.person.getId(),d=opensocial.newIdSpec({userId:c}),e=opensocial.newDataRequest();(this.state_.data.viewer&&c!=this.state_.data.viewer.getId()||this.isCanvasMode())&&e.add(gfc_Sa(b.person.getId(),"VIEWER"),"isProfileFriend");e.add(e.newFetchActivitiesRequest(d,{}),"activities");e.send(a)};
gfc_.processActivityData_=function(a,b){null!=a.get("activities").getData()&&(this.state_.data.profile.activities=a.get("activities").getData());var c=a.get("isProfileFriend");c&&b&&null!=this.state_.data.viewer&&this.state_.data.viewer.getId()!=b.person.getId()&&(this.state_.data.profile.isFriend=c.getData().value)};
gfc_.processProfileData_=function(a,b){var c=a.get("profile").getData();this.state_.data.profile.person=c;this.state_.data.profile.person.externalProfileUrl=null;var d=c.getField(opensocial.Person.Field.URLS),e=[];if(d)for(var f=0;f<d.length;f++){var g=d[f];"profile"!=g.getField(opensocial.Url.Field.TYPE)&&"externalProfile"!=g.getField(opensocial.Url.Field.TYPE)&&e.push(g);"externalProfile"==g.getField(opensocial.Url.Field.TYPE)&&(this.state_.data.profile.person.externalProfileUrl=g.getField(opensocial.Url.Field.ADDRESS))}this.state_.data.profile.links=
new gfc_mi(e,this.linksPageSize_,0);this.state_.data.owner=a.get("owner").getData();this.state_.data.viewer=a.get("viewer").getData();(d=this.state_.data.viewer)&&b.person.getId()!=this.state_.data.viewer.getId()&&(this.state_.data.profile.isAdmin=a.get("isAdmin").getData(),this.state_.data.profile.isAdmin&&(this.state_.data.profile.isAdmin=this.state_.data.profile.isAdmin.size()),this.state_.data.profile.isBlocked=a.get("isBlocked").getData(),this.state_.data.profile.isBlocked&&(this.state_.data.profile.isBlocked=
this.state_.data.profile.isBlocked.size()));c=c.getField("profileExtensions");c=this.util_.jsonToJSArray(c,this.util_.sortExtensions);d=[];for(f in c){e=c[f];g={};g.title=e.title;var h=!1;if("SHORT_TEXT"==e.entryType||"LONG_TEXT"==e.entryType)e.value&&e.value.text&&(g.body=[],g.body.push(e.value.text),h=!0);else if(e.value&&e.value.choice&&0<e.value.choice.length){g.body=[];for(h=0;h<e.value.choice.length;++h)g.body.push(e.value.choice[h].label);h=!0}h&&d.push(g)}this.state_.data.profile.profileExtensions=
d;this.siteSettings_||(this.siteSettings_=a.get("siteSettings").getData());this.isMessagingEnabled&&(f=(f=a.get("canMessage"))&&f.getData().canSendMessage,this.state_.data.profile.canSendMessage=f);this.setAdminHelper_(a)};gfc_.blockUser_=function(a){this.render(["blockUser"],"profile",{person:a})};gfc_.unblockUser_=function(a){this.render(["unblockUser"],"profile",{person:a})};gfc_.map=function(a,b){var c=[],d=gfc_k(function(a,b,c){a.push(b(c))},this,c,b);a.each(d);return c};
gfc_.showAllMembers_=function(){this.pushGoBack();this.invokeView("members-page")};gfc_.showBlockedMembers_=function(){this.pushGoBack();this.render(["blocked-member-page"],"blocked-members-page",{start:0})};gfc_.showUnblockedMembers_=function(){this.unwindGoBackStack()};gfc_.nextMembers_=function(a){this.render(["member-page"],"members-page",{start:this.maxFacesPerPage_+a.getOffset()})};gfc_.previousMembers_=function(a){this.render(["member-page"],"members-page",{start:a.getOffset()-this.maxFacesPerPage_})};
gfc_.nextBlockedMembers_=function(a){this.render(["blocked-member-page"],"blocked-members-page",{start:this.maxFacesPerPage_+a.getOffset()})};gfc_.previousBlockedMembers_=function(a){this.render(["blocked-member-page"],"blocked-members-page",{start:a.getOffset()-this.maxFacesPerPage_})};gfc_.showAllViewerFriends_=function(){this.pushGoBack();this.invokeView("viewer-friends-page")};
gfc_.nextViewerFriends_=function(a){this.render(["viewerFriends"],"viewer-friends-page",{start:this.maxFacesPerPage_+a.getOffset()})};gfc_.previousViewerFriends_=function(a){this.render(["viewerFriends"],"viewer-friends-page",{start:a.getOffset()-this.maxFacesPerPage_})};gfc_.showAllProfileFriends_=function(){this.pushGoBack();this.invokeView("profile-friends-page")};
gfc_.nextProfileFriends_=function(a){this.render(["profile-friends-page"],"profile-friends-page",{start:this.maxFacesPerPage_+a.getOffset(),person:this.state_.data.profile.person})};gfc_.previousProfileFriends_=function(a){this.render(["profile-friends-page"],"profile-friends-page",{start:a.getOffset()-this.maxFacesPerPage_,person:this.state_.data.profile.person})};gfc_.showAllLinks_=function(){this.pushGoBack();this.invokeView("links")};
gfc_.nextLinks_=function(a){var b=this.linksPageSize_+a.getOffset();this.state_.data.profile.links=new gfc_mi(a.all(),this.linksPageSize_,b);this.invokeView("links")};gfc_.previousLinks_=function(a){var b=a.getOffset()-this.linksPageSize_;this.state_.data.profile.links=new gfc_mi(a.all(),this.linksPageSize_,b);this.invokeView("links")};gfc_.showAllSites_=function(){this.pushGoBack();this.invokeView("sites")};
gfc_.nextSites_=function(a){this.render(["sitesData"],"sites",{start:this.sitesPageSize_+a.getOffset()})};gfc_.previousSites_=function(a){this.render(["sitesData"],"sites",{start:a.getOffset()-this.sitesPageSize_})};gfc_.showAllActivities_=function(){this.pushGoBack();this.invokeView("activities")};gfc_.nextActivities_=function(a){this.render(["activityData"],"activities",{start:this.activityPageSize_+a.getOffset()})};
gfc_.previousActivities_=function(a){this.render(["activityData"],"activities",{start:a.getOffset()-this.activityPageSize_})};gfc_.handleDeleteActivity=function(a){this.render(["deleteActivity"],this.state_.view,{activity:a})};gfc_.requestBlockUser_=function(a,b){var c=opensocial.newDataRequest();c.add(gfc_Ua(b.person.getId(),["BLOCKED"],[]),"block");this.invalidateGoBackStack();c.send(a)};gfc_.processBlockUser_=function(a){if(a=!a.get("block").hadError())this.state_.data.profile.isBlocked=!0};
gfc_.requestUnblockUser_=function(a,b){var c=opensocial.newDataRequest();c.add(gfc_Ua(b.person.getId(),[],["BLOCKED"]),"unblock");this.invalidateGoBackStack();c.send(a)};gfc_.processUnblockUser_=function(a){if(a=!a.get("unblock").hadError())this.state_.data.profile.isBlocked=!1};
gfc_.requestDeleteActivity_=function(a,b){var c=b.activity,d=c.getField(opensocial.Activity.Field.ID),c=opensocial.newIdSpec({userId:c.getField(opensocial.Activity.Field.USER_ID)}),e=opensocial.newDataRequest();e.add(gfc_Ea(d),"delete");e.add(e.newFetchActivitiesRequest(c,{}),"activities");e.send(a)};
gfc_.transformActivity_=function(a){var b=function(a){return a=a.replace(/<a/g,"<a target='_top'")},c=null,d=this.state_.data.viewer;null!=d&&a.getField(opensocial.Activity.Field.USER_ID)==this.state_.data.viewer.getId()&&(c=gfc_k(this.handleDeleteActivity,this,a));(d=a.getField(opensocial.Activity.Field.STREAM_FAVICON_URL,{escapeType:"none"}))||(d=window.friendconnect_imageUrl+"/favicons.gif");return{icon:d,time:gfc_4h(Number(a.getField(opensocial.Activity.Field.POSTED_TIME))),link:a.getField(opensocial.Activity.Field.STREAM_URL,
{escapeType:"none"}),siteTitle:a.getField(opensocial.Activity.Field.STREAM_TITLE,{escapeType:"none"}),innerHTML:b(a.getField(opensocial.Activity.Field.TITLE,{escapeType:"none"})),body:b(a.getField(opensocial.Activity.Field.BODY,{escapeType:"none"})),deleteHandler:c}};gfc_.transformSite_=function(a){var b=gadgets.util.unescapeString;return{icon:gfc_ji(a.getField(opensocial.Person.Field.PROFILE_URL)),link:a.getField(opensocial.Person.Field.PROFILE_URL),title:b(a.getDisplayName())}};
gfc_.transformLink_=function(a){var b=gadgets.util.unescapeString,c=a.getField(opensocial.Url.Field.ADDRESS);return{icon:gfc_ji(c),link:c,title:b(a.getField(opensocial.Url.Field.LINK_TEXT))||c}};
gfc_.requestProfileFriends_=function(a,b){var c=opensocial.newDataRequest(),d=b.person.getId(),e=opensocial.DataRequest.PeopleRequestFields,f=this.newFriendsIdSpec(d),g={};g[opensocial.DataRequest.DataRequestFields.ESCAPE_TYPE]=opensocial.EscapeType.NONE;c.add(c.newFetchPeopleRequest(f,g),"friends");f={};f[e.FIRST]=this.sitesStartIndex_;f[e.MAX]=this.sitesCount_;c.add(gfc_Va(opensocial.newIdSpec({userId:d}),f),"profileSites");c.send(a)};
gfc_.ignoreFriendRequest_=function(a){a={user:a.getId(),action:"DENY"};this.render(["sendFriendRequestResponse","members","viewerFriends"],gfc_k(this.chooseViewAfterFriendRequest_,this),{friendRequestResponses:[a]})};gfc_.chooseViewAfterFriendRequest_=function(a){return a&&a["next-view"]?a["next-view"]:["friend-requests"]};gfc_.requestSendFriendRequest_=function(a,b){var c=b.profile,d=opensocial.newDataRequest();d.add(gfc_Fa(c.getId(),b.message),"friendRequest");this.invalidateGoBackStack();d.send(a)};
gfc_.processSendFriendRequest_=function(a){a.get("friendRequest").hadError()||(this.state_.data.profile.isInvited=!0)};gfc_.requestFriendRequestResponse_=function(a,b){var c=osapi.newBatch(),d=b.friendRequestResponses;c.add("updateFriendRequest",osapi.extensions.get({command:"ProcessFriendRequests",params:'{"requests":'+gadgets.json.stringify(d)+"}"}));c.add("friendRequests",osapi.extensions.get({command:"GetFriendRequests",params:'{"idSpec" : "VIEWER"}'}));this.invalidateGoBackStack();c.execute(a)};
gfc_.goToInviteFriend_=function(){this.pushGoBack();this.invokeView("invite-friend")};gfc_.sendMessageDialogWrapper_=function(a){this.isMessagingEnabled&&(a=a.getField(opensocial.Person.Field.ID),this.sendMessageDialog_(a))};gfc_.sendMessageDialog_=function(a){this.isMessagingEnabled&&(a="/friendconnect/messaging/compose?recipientId="+a,gfc_Qh(a,"570","395"))};gfc_7.prototype.acceptMessages=function(){gfc_Qh("/friendconnect/messaging/accept","570","375");return!1};gfc_=gfc_li.prototype;
gfc_.goToBlockMember_=function(){this.pushGoBack();this.invokeView("block-member")};gfc_.goToViewerProfile_=function(){this.viewProfile_(this.state_.data.viewer)};gfc_.sendInvite_=function(a){this.popGoBack();a={profile:a};var b=gfc_E("inviteMessage");b&&(a.message=gfc_1c(b));this.render(["sendFriendRequest"],"profile",a)};gfc_.blockMember_=function(a){this.popGoBack();this.blockUser_(a)};
gfc_.processFriendRequestResponse_=function(a,b,c){c=c||!1;this.state_.data.friendRequests=gfc_Qa(a.friendRequests,gfc_Ha);0<this.state_.data.friendRequests.size()?b["next-view"]="friend-requests":b["next-view"]="faces";c||gfc_5("friend")};gfc_.processProfileFriends_=function(a){this.state_.data.profile.sites=a.get("profileSites").getData();this.state_.data.profile.friends=a.get("friends").getData()};gfc_.getShowInvitedBy_=function(){return this.showInvitedBy_};
gfc_.renderDone=function(){this.optionsMenuWrapper_.rebuild();this.addPromoDismissHandler();gadgets.window.adjustHeight()};gfc_.optionsMenuButtonBuilder=function(a){return a=gfc_G("span",{"class":"fc-cap-link-big"},gfc_G("a",{"class":"fc-cap-link-big"},this.defaultThemeMsgs_.MSG_OPTIONS),a.createTriangleSpan())};
gfc_.optionsMenuBoxBuilder=function(){var a=[];a[a.length]=gfc_G("div",{"class":"goog-menuitem menuaction-settings"},this.defaultThemeMsgs_.MSG_SITE_SETTINGS);this.isSocialShareEnabled&&(a[a.length]=gfc_G("div",{"class":"goog-menuitem menuaction-share"},this.defaultThemeMsgs_.MSG_MEMBERS_SHARE));this.state_.data.isViewerAdmin&&!this.isCanvasMode()&&(a[a.length]=gfc_G("div",{"class":"goog-menuitem menuaction-manage"},this.defaultThemeMsgs_.MSG_MANAGE));a[a.length]=gfc_G("div",{"class":"goog-menuitem menuaction-signout"},
this.siteSettings_.signOutPrompt||this.defaultThemeMsgs_.MSG_SIGN_OUT);a[a.length]=gfc_G("div",{"class":"goog-menuseparator fc-menuseparator-line"});a[a.length]=gfc_G("div",{"class":"goog-menuitem menuaction-aboutfc"},gfc_G("span",{"class":"fc-small-menu-link"},this.defaultThemeMsgs_.MSG_ABOUT_FC));return a};
gfc_.optionsMenuHandler_=function(a){a.stopPropagation();a=a.target.getElement().className;a.match("menuaction-settings")?this.editSettings():a.match("menuaction-share")?this.share():a.match("menuaction-signout")?this.signout():a.match("menuaction-manage")?this.gotoManageMembers_():a.match("menuaction-aboutfc")&&(a=window.open(gfc_Jh()+"/friendconnect/home/overview"),a.focus())};
gfc_.gotoManageMembers_=function(){var a={},b=gadgets.views.getSupportedViews().canvas;gfc_5("lightbox");gadgets.views.requestNavigateTo(b,a);return!1};for(var gfc_ki,gfc_ni="HEIGHT BORDER_COLOR CONTENT_BG_COLOR CONTENT_HEADLINE_COLOR CONTENT_LINK_COLOR CONTENT_SECONDARY_TEXT_COLOR CONTENT_SECONDARY_LINK_COLOR CONTENT_TEXT_COLOR ENDCAP_BG_COLOR ENDCAP_LINK_COLOR ENDCAP_TEXT_COLOR FACE_SIZE NUMBER_ROWS".split(" "),gfc_oi={},gfc_pi=0;gfc_pi<gfc_ni.length;++gfc_pi)gfc_oi[gfc_ni[gfc_pi]]=gfc_ni[gfc_pi];
gfc_ki=gfc_oi;
gfc_li.prototype.createCss=function(){var a=gfc_ki,b=[],c=0;this.getSkinProperty(a.HEIGHT);this.isProfileMode()&&(b[c++]=this.subIfNotNull(".fc-thumbnail img {height:%spx;width:%spx}",this.getSkinProperty(a.FACE_SIZE)));b[c++]=this.subIfNotNull(".fc-scroll-botnav, .fc-scroll, .fc-noscroll-botnav {height: %spx;}\n",this.scrollHeight_);b[c++]=this.subIfNotNull(".fc-members,.fc-members-canvas {border-color: %s;}\n.fc-userpage-itemlist,.fc-userpage-itemlist-canvas,.fc-botcap-short { border-top-color: %s; }\n.fc-topcap,.fc-topverb,.fc-friendreq,.fc-friendreqs,.fc-timeframe { border-bottom-color: %s; }\n",this.getSkinProperty(a.BORDER_COLOR));
this.isMenu()&&(this.hasMenuMode("profile")?b[c++]=".fc-topcap {height: "+this.slimTopCapHeight+"px;}\n":this.isTopMenu()?b[c++]=".fc-topcap {height: 0px;}\n":b[c++]=".fc-topcap {height: "+this.tinyTopCapHeight+"px;}\n");this.isCanvasMode()?b[c++]=".fc-userpic-caption {margin-left: 59px;}\n":b[c++]=".fc-userpic-caption {margin-left: 40px;}\n";this.isTopMenu()?b[c++]=".fc-topcap-color {background-color: white;}\n":b[c++]=this.subIfNotNull(".fc-topcap-color {background-color: %s;}\n",this.getSkinProperty(a.ENDCAP_BG_COLOR));
this.isBottomMenu()?b[c++]=".fc-botcap-short {background-color: white;}\n":b[c++]=this.subIfNotNull(".fc-botcap-short {background-color: %s;}\n",this.getSkinProperty(a.ENDCAP_BG_COLOR));b[c++]=this.subIfNotNull(".fc-botverb, .fc-topverb, .fc-members-header {background-color: %s;}\n",this.getSkinProperty(a.ENDCAP_BG_COLOR));b[c++]=this.subIfNotNull(".fc-botverb, .fc-topverb, .fc-members-header {background-color: %s;}\n",this.getSkinProperty(a.ENDCAP_BG_COLOR));b[c++]=this.subIfNotNull(".fc-topcap, .fc-botverb, .fc-topverb, .fc-botcap-short, .fc-header-sectitle, .fc-members-header {color: %s;}\n",
this.getSkinProperty(a.ENDCAP_TEXT_COLOR));b[c++]=this.subIfNotNull(".fc-botverb,.fc-topcap .fc-menutriangle-down, .fc-topcap .fc-menutriangle-up,.fc-topcap a, .fc-topcap a:active, .fc-topcap a:visited,.fc-topcap-link a, .fc-topcap-link a:active, .fc-topcap-link a:visited,.fc-cap-link-big a, .fc-cap-link-big a:active,.fc-left-verb a, .fc-left-verb a:active, .fc-left-verb a:visited,.fc-right-verb a, .fc-right-verb a:active, .fc-right-verb a:visited,.fc-subtle-botcap a, .fc-subtle-botcap a:active, .fc-subtle-botcap a:visited.fc-left-verb-canvas a, .fc-left-verb-canvas a:active, .fc-left-verb-canvas a:visited,.fc-right-verb-canvas a, .fc-right-verb-canvas a:active, .fc-right-verb-canvas a:visited {color: %s;}\n",
this.getSkinProperty(a.ENDCAP_LINK_COLOR));b[c++]=this.subIfNotNull(".fc-content-bg, .fc-subtle-botcap {background-color:%s;}\n",this.getSkinProperty(a.CONTENT_BG_COLOR));b[c++]=this.subIfNotNull(".fc-content a, .fc-content a:active, .fc-content a:visited,\n.fc-item-body a, .fc-item-body a:active, .fc-item-body a:visited,\n.fc-see-all a, .fc-see-all a:active, .fc-see-all a:visited,\n.fc-content-link a, .fc-content-link a:active, .fc-content-link a:visited,\n.fc-content-canvas a, .fc-content-canvas a:active, .fc-content-canvas a:visited {color: %s;}\n",
this.getSkinProperty(a.CONTENT_LINK_COLOR));b[c++]=this.subIfNotNull(".fc-members,.fc-members-canvas {color:%s;}\n",this.getSkinProperty(a.CONTENT_TEXT_COLOR));b[c++]=this.subIfNotNull(".fc-helpful,.fc-on-other-site,.fc-no-elements, .ot-activity-metadata {color:%s;}\n",this.getSkinProperty(a.CONTENT_SECONDARY_TEXT_COLOR));b[c++]=this.subIfNotNull(".fc-faded-link a, .fc-faded-link a:active, .fc-faded-link a:visited, .fc-faded-link-small a, .fc-faded-link-small a:active, .fc-faded-link-small a:visited {color: %s;}\n",
this.getSkinProperty(a.CONTENT_SECONDARY_LINK_COLOR));b[c++]=this.subIfNotNull(".fc-sectitle {color: %s;}\n",this.getSkinProperty(a.CONTENT_HEADLINE_COLOR));return gfc_li.superClass_.createCss.call(this)+b.join("\n")};gfc_e("goog.peoplesense.gadget.Members",gfc_li,void 0);gfc_e("goog.peoplesense.gadget.Members.start",gfc_li.start,void 0);var gfc_mi=function(a,b,c){opensocial.Collection.call(this,a.slice(c,c+b),c,a.length);this.all_=a;this.pageSize_=b};gfc_m(gfc_mi,opensocial.Collection);
gfc_mi.prototype.all=function(){return this.all_};gfc_mi.prototype.getPageSize=function(){return this.pageSize_};gfc_e("goog.peoplesense.gadget.Members.PagedCollection.prototype.all",gfc_mi.prototype.all,void 0);gfc_e("goog.peoplesense.gadget.Members.PagedCollection.prototype.getPageSize",gfc_mi.prototype.getPageSize,void 0);
