(function(g){var window=this;var f$=function(a,b){return g.aa[a]=b},vsa=function(a,b){var c=(0,g.O)(b,function(a){return g.Uq(a)});
g.$q({visibilityUpdate:{csn:a,visualElements:c}})},g$=function(a,b,c,d){var e=b.zb();
g.K(a.element,"ytp-suggestion-set",!!e.videoId);var f=b.Qg();d=b.zc(c,d?d:"mqdefault.jpg");var k=b instanceof g.SF?g.Rq(b.lengthSeconds):null,l=!!f,f=l&&"RD"==g.ZK(f).type;c={title:b.title,author:b.author,author_and_views:e.shortViewCount?b.author+" \u2022 "+e.shortViewCount:b.author,watch:g.P("YTP_WATCH_VIDEO_OR_PLAYLIST",{TITLE:b.title},b.title),duration:k,url:b.Bl(c),episodic_title:b.title,is_episodic:e.km,is_featured:e.rq,is_list:l,is_mix:f,background:d?"background-image: url("+d+")":""};b instanceof
g.aL&&(c.playlist_length=b.A,c.episodic_length=b.A,c.episodic_index=b.Xb());a.update(c)},h$=function(a,b){g.rG.call(this,{la:"div",
Gc:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.o=a;this.N=!1},i$=function(){g.S.call(this,["div",
"ytp-subscribe-card",["img","ytp-author-image",{src:"{{image}}"}],["div","ytp-subscribe-card-right",["div","ytp-author-name","{{author}}"],["div","html5-subscribe-button-container"]]])},j$=function(a){g.k5.call(this,a,{la:"div",
Gc:["ytp-thumbnail-overlay","ytp-channel-overlay"],va:[{la:"div",wa:"ytp-thumbnail-overlay-image",Fc:{style:"{{background}}"}},{la:"div",wa:"ytp-thumbnail-overlay-curtain"}]})},k$=function(a){h$.call(this,a,"subscribecard-endscreen");
this.B=new j$(a);g.G(this,this.B);g.Ev(this.o,this.B.element,4);this.C=new i$;g.G(this,this.C);this.fa()},l$=function(a){var b=g.T(a).experiments.aa("moving_thumbnails_autonav"),c=["img",
"ytp-upnext-moving-thumbnail",{src:"{{moving_thumbnail}}"}],c=["div","ytp-upnext",{"aria-label":"{{watch}}"},["div","ytp-thumbnail-overlay-image",{style:"{{background}}"}],b?c:null,["div","ytp-thumbnail-overlay-curtain"],["span","ytp-upnext-top",["span","ytp-upnext-header",g.P("YTP_PLAYLIST_UP_NEXT")],["span","ytp-upnext-title","{{title}}"],["span","ytp-upnext-author","{{author}}"]],["a","ytp-upnext-autoplay-icon",{href:"{{url}}"}],["span","ytp-upnext-bottom",["span","ytp-upnext-cancel"],["span",
"ytp-upnext-paused",g.P("YTP_AUTOPLAY_PAUSED_2")]],["span","ytp-upnext-close"]];g.S.call(this,c);var d=this.na["ytp-upnext-cancel"],c=this.na["ytp-upnext-close"],e=new g.S(["button",["ytp-upnext-cancel-button","ytp-button"],{tabindex:0,"aria-label":g.P("YTP_AUTOPLAY_CANCEL")},g.P("YTP_CANCEL")]);g.G(this,e);e.O("click",this.Tq,this);e.b(d);d=new g.S(["button",["ytp-upnext-close-button","ytp-button"]]);g.G(this,d);d.O("click",this.Tq,this);d.b(c);c=this.na["ytp-upnext-autoplay-icon"];g.yh(c,'<svg height="100%" version="1.1" viewBox="0 0 98 98" width="100%"><circle class="ytp-svg-autoplay-circle" cx="49" cy="49" fill="#000" fill-opacity="0.8" r="48" /><circle class="ytp-svg-autoplay-ring" cx="-49" cy="49" fill-opacity="0" r="46.5" stroke="#FFFFFF" stroke-dasharray="293" stroke-dashoffset="-293" stroke-width="4" transform="rotate(-90)" /><polygon class="ytp-svg-autoplay-triangle" fill="#fff" points="32,27 72,49 32,71" /></svg>');
this.B=a;this.J=g.rf("ytp-svg-autoplay-ring",this.element);this.F=this.D=this.o=this.C=null;this.G=new g.fe(this.Mi,5E3,this);g.G(this,this.G);this.H=0;this.R(c,"click",this.OC);this.Sq();this.R(a,"autonavvisibility",this.Sq);b&&this.R(this.na["ytp-upnext-moving-thumbnail"],"load",this.DI)},m$=function(a){a.o||(g.fj("a11y-announce",g.P("YTP_PLAYLIST_UP_NEXT")+" "+a.C.title),a.H=(0,g.zq)(),a.o=new g.fe(a.Ik,25,a),a.Ik());
g.le(a.element,"ytp-upnext-autoplay-paused")},o$=function(a){n$(a);
a.H=(0,g.zq)();a.Ik();g.J(a.element,"ytp-upnext-autoplay-paused")},n$=function(a){a.o&&(a.o.dispose(),a.o=null)},p$=function(a){var b=g.T(a),c=b.experiments.aa("video_wall_moving_thumbnails_hover"),c=b.experiments.aa("video_wall_moving_thumbnails_autoplay")||c,d=b.experiments.aa("video_wall_redesign");
this.D=b.C;var b=d&&(g.$l||g.Fc)?{style:"will-change: opacity"}:null,e={la:"img",wa:"ytp-videowall-moving-thumbnail",Fc:{src:"{{moving_thumbnail}}"}};g.S.call(this,{la:"a",wa:"videowall-still",Fc:{href:"{{url}}",target:this.D?"_blank":null,"aria-label":"{{watch}}","data-is-episodic":"{{is_episodic}}","data-is-featured":"{{is_featured}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},va:[{la:"div",wa:d?"ytp-redesign-videowall-still-image":"videowall-still-image",Fc:{style:"{{background}}"}},
c?e:null,{la:"span",wa:"videowall-still-featured-label",va:[g.P("YTP_FEATURED")]},{la:"span",wa:d?"ytp-redesign-videowall-still-info":"videowall-still-info",va:[{la:"span",wa:d?"ytp-redesign-videowall-still-info-bg":"videowall-still-info-bg",va:[{la:"span",wa:d?"ytp-redesign-videowall-still-info-content":"videowall-still-info-content",Fc:b,va:[{la:"span",wa:d?"ytp-redesign-videowall-still-info-title":"videowall-still-info-title",va:["{{title}}"]},{la:"span",wa:d?"ytp-redesign-videowall-still-info-author":
"videowall-still-info-author",va:["{{author_and_views}}"]},{la:"span",wa:d?"ytp-redesign-videowall-still-info-duration":"videowall-still-info-duration",va:["{{duration}}"]}]}]}]},{la:"div",Gc:["videowall-still-listlabel-episodic",d?"ytp-redesign-videowall-still-listlabel":"videowall-still-listlabel"],va:[{la:"div",wa:"videowall-still-listlabel-episodic-heading",va:[g.P("YTP_PLAYLIST_UP_NEXT")]},{la:"span",wa:"videowall-still-listlabel-episodic-icon"},{la:"div",wa:"videowall-still-listlabel-episodic-info",
va:[{la:"span",wa:"videowall-still-listlabel-episodic-index",va:[{la:"span",va:["{{episodic_index}}"]}," / ",{la:"span",va:["{{episodic_length}}"]}]},{la:"span",va:["{{episodic_title}}"]}]}]},{la:"span",Gc:["videowall-still-listlabel-regular",d?"ytp-redesign-videowall-still-listlabel":"videowall-still-listlabel"],va:[{la:"span",wa:"videowall-still-listlabel-icon"},g.P("YTP_PLAYLIST"),{la:"span",wa:"videowall-still-listlabel-length",va:[" (",{la:"span",va:["{{playlist_length}}"]},")"]}]},{la:"span",
Gc:["videowall-still-listlabel-mix",d?"ytp-redesign-videowall-still-listlabel":"videowall-still-listlabel"],va:[{la:"span",wa:"videowall-still-listlabel-mix-icon"},g.P("YTP_MIX"),{la:"span",wa:"videowall-still-listlabel-length",va:[" (50+)"]}]}]});this.B=a;this.o=null;this.F=new g.fe(this.Es,6E3,this);this.O("click",this.TG);this.O("keypress",this.UG);c&&this.R(this.na["ytp-videowall-moving-thumbnail"],"load",this.WG)},q$=function(a){if(5E5<g.EG(a.B.app.ka)){var b=a.o.ih();
b&&a.update({moving_thumbnail:b})}},r$=function(a,b){h$.call(this,a,"videowall-endscreen");
this.ba=a;this.$=b;this.H=0;this.D=[];this.J=this.F=this.B=null;this.K=this.W=!1;this.G=new g.Yw(this);g.G(this,this.G);this.L=new g.fe(g.ta(g.J,this.element,"ytp-show-tiles"),0);g.G(this,this.L);var c=g.T(this.o).experiments.aa("video_wall_pagination");if(c){var d=new g.S({la:"button",Gc:["ytp-button","ytp-endscreen-previous"],Fc:{"aria-label":g.P("YTP_PREVIOUS")}});g.G(this,d);g.yh(d.element,'<svg height="100%" version="1.1" viewBox="0 0 32 32" width="100%"><path d="M 19.41,20.09 14.83,15.5 19.41,10.91 18,9.5 l -6,6 6,6 z" fill="#fff" /></svg>');
d.b(this.element);d.O("click",this.kB,this)}this.V=new g.Iq({la:"div",wa:"ytp-endscreen-content"});g.G(this,this.V);this.V.b(this.element);c&&(c=new g.S({la:"button",Gc:["ytp-button","ytp-endscreen-next"],Fc:{"aria-label":g.P("YTP_NEXT")}}),g.G(this,c),g.yh(c.element,'<svg height="100%" version="1.1" viewBox="0 0 32 32" width="100%"><path d="m 12.59,20.34 4.58,-4.59 -4.58,-4.59 1.41,-1.41 6,6 -6,6 z" fill="#fff" /></svg>'),c.b(this.element),c.O("click",this.jB,this));g.T(this.o).experiments.aa("video_wall_redesign")&&
g.J(this.element,"ytp-endscreen-redesign");this.C=new l$(a);g.G(this,this.C);g.Ev(this.o,this.C.element,4);this.fa()},s$=function(a){return g.bK(a.o)&&a.Nk()&&!a.J},t$=function(a){return(0,g.O)(a.H,function(a){return g.z4(a)})},u$=function(a,b,c){return 0==b&&a.B.length&&(b=c/r$.b,c/=r$.b,3<=b&&3<=c&&a.B[0].zb().km||2<=b&&2<=c&&g.T(a.o).experiments.aa("video_wall_emphasize_first"))?2*r$.b:r$.b},v$=function(a){var b=a.$.Kn();
b!=a.W&&(a.W=b,a.o.Sa("autonavvisibility"))},x$=function(a){g.gL.call(this,a);
g.Xi({});this.g=null;this.o=new g.Yw(this);g.G(this,this.o);var b=g.T(a);w$(a)?this.g=new r$(this.b,this):b.ba?this.g=new k$(this.b):this.g=new h$(this.b);g.G(this,this.g);g.Ev(this.b,this.g.element,4);this.Xr();this.o.R(a,"videodatachange",this.Xr,this);this.o.R(a,"crn_endscreen",this.AB,this);this.o.R(a,"crx_endscreen",this.BB,this)},w$=function(a){a=g.T(a);
return a.dd&&!a.ba};
g.SF.prototype.ih=f$(1,function(){return this.te});
g.aL.prototype.ih=f$(0,function(){return null});g.y(h$,g.rG);h$.prototype.create=function(){this.N=!0};
h$.prototype.destroy=function(){this.N=!1};
h$.prototype.Nk=function(){return!1};g.y(i$,g.S);g.y(j$,g.k5);j$.prototype.gb=function(a){a?this.B.show():this.B.fa()};g.y(k$,h$);k$.prototype.create=function(){k$.M.create.call(this);g.Gf(this.element);this.C.b(this.element);var a=this.o.getVideoData().videoId;a&&(a=g.tB(g.T(this.o),a,!0),g.Yj(a,{method:"GET",cb:this.D,context:this,yx:!0}))};
k$.prototype.D=function(a,b){if(this.N){var c=b.user_info,d=c.channel_banner_url;g.sB.test(d)||(d="");var e=c.channel_logo_url||c.image_url;g.sB.test(e)||(e="");this.B.g("background",d?"background-image: url("+d+")":"");this.C.g("image",e);this.C.g("author",c.channel_title||c.username);c=c.subscription_button_html;d=this.C.na["html5-subscribe-button-container"];c?d.innerHTML=g.Oe(c):g.Gf(d)}};
k$.prototype.show=function(){k$.M.show.call(this);this.B.gb(!0)};
k$.prototype.fa=function(){k$.M.fa.call(this);this.B.gb(!1)};g.y(l$,g.S);g.h=l$.prototype;g.h.Mi=function(){this.D&&(this.G.stop(),this.qa(this.F),this.F=null,this.D.close(),this.D=null)};
g.h.Sq=function(){this.gb(g.LJ(this.B))};
g.h.GC=function(){window.focus();this.Mi()};
g.h.fa=function(){l$.M.fa.call(this)};
g.h.Ik=function(){var a=Math.min((0,g.zq)()-this.H,1E4),a=Math.min(a/1E4,1);this.J.setAttribute("stroke-dashoffset",-293*(a+1));1<=a?this.select(!0):this.o&&this.o.start()};
g.h.select=function(a){var b=g.T(this.B);if(b.experiments.aa("autonav_notifications")&&a&&window.Notification&&window.document.hasFocus){var c=window.Notification.permission;g.Mu(this.B,"xwebnotifications",{permission:c});"default"==c?window.Notification.requestPermission():"granted"!=c||window.document.hasFocus()||(c=this.C.zb(),this.Mi(),this.D=new window.Notification(g.P("YTP_PLAYLIST_UP_NEXT"),{body:c.title,icon:c.zc(b)}),this.F=this.R(this.D,"click",this.GC),this.G.start())}n$(this);b=this.C.zb().videoId;
g.N8(this.B.app,b,a?this.C.Jc:this.C.W,this.C.Qg(),void 0)};
g.h.OC=function(a){!g.sm(a)&&g.Sq(a)&&(this.select(),g.rm(a))};
g.h.Tq=function(a){g.rm(a);g.TJ(this.B,"autonavcancel");g.OJ(this.B,!0)};
g.h.DI=function(a){120<g.nm(a).naturalWidth&&g.J(this.element,"ytp-moving-thumbnail-loaded")};
g.h.P=function(){n$(this);this.Mi();l$.M.P.call(this)};g.y(p$,g.S);g.h=p$.prototype;g.h.Bg=function(){var a=this.o.zb().videoId;g.N8(this.B.app,a,this.o.W,this.o.Qg(),void 0)};
g.h.TG=function(a){g.ar(a,this.B,!this.B.Na()&&this.D,this.o.W)&&this.Bg()};
g.h.VG=function(){this.qa(this.C);this.C=null;q$(this)};
g.h.UG=function(a){switch(a.keyCode){case 13:case 32:g.sm(a)||(this.Bg(),g.rm(a))}};
g.h.WG=function(a){120<g.nm(a).naturalWidth&&(g.J(this.element,"ytp-videowall-moving-thumbnail-loaded"),this.F.start())};
g.h.Es=function(){g.le(this.element,"ytp-videowall-moving-thumbnail-loaded")};g.y(r$,h$);r$.b=2;g.h=r$.prototype;g.h.create=function(){r$.M.create.call(this);var a=this.o.getVideoData();a&&(this.B=t$(a),this.F=a);this.Ze();this.G.R(this.o,"appresize",this.Ze);this.G.R(this.o,"videodatachange",this.SG);this.G.R(this.o,"autonavchange",this.Qt);this.G.R(this.o,"autonavcancel",this.ay);this.G.R(this.element,"transitionend",this.KD)};
g.h.destroy=function(){g.$w(this.G);g.Sb(this.D);this.D=[];this.B=null;r$.M.destroy.call(this);g.le(this.element,"ytp-show-tiles");this.L.stop()};
g.h.Nk=function(){return 1!=this.F.autonavState};
g.h.show=function(){r$.M.show.call(this);g.le(this.element,"ytp-show-tiles");g.T(this.o).isMobile?g.ge(this.L):this.L.start();(this.K||this.J&&this.J!=this.F.clientPlaybackNonce)&&g.OJ(this.o,!1);var a=s$(this);g.bK(this.o)&&g.T(this.o).experiments.aa("ui_logging")&&this.$.log({cancelButtonShow:a?"1":"0",state:this.Nk()?"enabled":"disabled"});a?(v$(this),2==this.F.autonavState?g.T(this.o).experiments.aa("fast_autonav_in_background")&&3==this.o.getVisibilityState()?this.C.select(!0):m$(this.C):3==
this.F.autonavState&&o$(this.C)):(g.OJ(this.o,!0),v$(this))};
g.h.fa=function(){r$.M.fa.call(this);o$(this.C);v$(this)};
g.h.KD=function(a){g.nm(a)==this.element&&this.Ze()};
g.h.Ze=function(){if(this.B&&this.B.length){var a=g.T(this.o),b=a.experiments.aa("video_wall_moving_thumbnails_hover"),c=a.experiments.aa("video_wall_pagination"),d=a.experiments.aa("video_wall_redesign");c&&g.J(this.element,"ytp-endscreen-paginate");var e=g.Cs(this.element),f=96,k=54,l=e.width/e.height,m=f/k;!g.br(a)||this.o.Na()||d||(f*=.9,k*=.9);var n=a=0;d&&(n=a=r$.b);var t=Math.max(e.width/f,2),u=Math.max(e.height/k,2),x=this.B.length,D=Math.pow(r$.b,2),z=x*D,H=u$(this,0,u),Q=u$(this,1,u),z=
z+(Math.pow(H,2)-D),z=z+(Math.pow(Q,2)-D);for(d&&(z-=D);0<z&&(a<t||n<u);){var L=a/r$.b,ma=n/r$.b,Ia=a<=t-r$.b&&z>=ma*D,Xa=n<=u-r$.b&&z>=L*D;if((d?(L+1)/ma*m/l>l/(L/(ma+1)*m):L/ma*m>l)&&Xa)z-=L*D,n+=r$.b;else if(Ia)z-=ma*D,a+=r$.b;else if(Xa)z-=L*D,n+=r$.b;else break}m=!1;t=r$.b+H;z>=3*D&&6>=x*D-z&&(n>=t||a>=t)&&Q<=r$.b&&(m=!0);f*=a;k*=n;l=f/k<l?e.height/k:e.width/f;l=Math.min(l,d?2:1.42);f*=l;k*=l;f*=g.af(e.width/f||1,1,1.21);k*=g.af(e.height/k||1,1,1.21);f=Math.floor(Math.min(e.width,f));k=Math.floor(Math.min(e.height,
k));e=this.V.element;g.As(e,f,k);g.is(e,{marginLeft:f/-2+"px",marginTop:k/-2+"px"});l=this.C;D=this.B[0];l.C=D;g$(l,D,g.T(l.B),"hqdefault.jpg");g.le(l.element,"ytp-moving-thumbnail-loaded");l.update({moving_thumbnail:"data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7"});5E5<g.EG(l.B.app.ka)&&(D=l.C.ih())&&l.update({moving_thumbnail:D});g.K(this.element,"ytp-endscreen-takeover",s$(this));v$(this);d=d?4:1;l=f+d;f=k+d;k=0;D=!s$(this);z=!1;for(t=0;t<a;t++)for(u=0;u<n;u++)if(L=
Q>r$.b&&1<=k&&!z?k+1:k,ma=0,m&&t>=a-r$.b&&u>=n-r$.b?ma=1:0==u%r$.b&&0==t%r$.b&&(u<H&&t<H?0==u&&0==t&&(ma=H):Q>r$.b&&u>=n-Q&&t>=a-Q?u==n-Q&&t==a-Q&&(z=!0,L=1,ma=Q):ma=r$.b),L=(L+this.H)%x,L=0>L*x?L+x:L,0!=ma){Ia=this.D[k];Ia||(Ia=new p$(this.o),this.D[k]=Ia,e.appendChild(Ia.element));var Xa=Math.floor(f*u/n),tb=Math.floor(l*t/a),Ze=Math.floor(f*(u+ma)/n)-Xa-d,Dk=Math.floor(l*(t+ma)/a)-tb-d;g.os(Ia.element,tb,Xa);g.As(Ia.element,Dk,Ze);g.is(Ia.element,"transitionDelay",(u+t)/20+"s");g.K(Ia.element,
"videowall-still-mini",1==ma);g.K(Ia.element,"videowall-still-large",2<ma);ma=Ia;L=this.B[L];Ia=D&&!b;ma.o=L;Xa=g.T(ma.B);g$(ma,L,Xa,g.ie(ma.element,"videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg");ma.Es();ma.F.stop();ma.update({moving_thumbnail:"data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7"});Ia?(g.J(ma.element,"ytp-videowall-active"),q$(ma)):Xa.experiments.aa("video_wall_moving_thumbnails_hover")&&!ma.C&&(ma.C=ma.O("mouseover",ma.VG));k++}c&&g.K(this.element,
"ytp-endscreen-paginate",k<x);for(b=this.D.length-1;b>=k;b--)Ia=this.D[b],g.If(Ia.element),g.Rb(Ia);this.D.length=k}};
r$.o=1.42;r$.g=1.21;g.h=r$.prototype;g.h.SG=function(){var a=this.o.getVideoData();this.F!=a&&(this.H=0,this.B=t$(a),this.F=a,this.Ze())};
g.h.jB=function(){this.H+=this.D.length;this.Ze()};
g.h.kB=function(){this.H-=this.D.length;this.Ze()};
g.h.Qt=function(a){1==a?(this.K=!1,this.J=this.F.clientPlaybackNonce,n$(this.C),this.A&&this.Ze()):(this.K=!0,this.A&&s$(this)&&(2==a?m$(this.C):3==a&&o$(this.C)))};
g.h.ay=function(a){if(a){a=[];for(var b=0;b<this.B.length;b++){var c=this.B[b].W;c&&a.push(c.itct)}b=this.ba;if(g.T(b).experiments.aa("player_interaction_logging")&&(b=b.app.dd,c=g.Zq())){for(var d=[],e=0;e<a.length;e++){var f=a[e];b.b[f]||(d.push(new g.Tq(f)),b.b[f]=!0)}0<d.length&&vsa(c,d)}this.Qt(1)}else this.J=null,this.K=!1;this.Ze()};g.y(x$,g.gL);g.h=x$.prototype;g.h.Lt=function(){var a=this.b.getVideoData(),b=!w$(this.b)||!(!a.H||!a.H.length),a=g.Xr(a,"ypc_module"),c=g.m5(this.b.app);return b&&!a&&!c};
g.h.Kn=function(){return this.g instanceof r$&&this.g.A&&s$(this.g)};
g.h.Yz=function(){return this.Kn()?!!this.g.C.o:!1};
g.h.P=function(){var a=this.b;g.gq(a.app,"endscreen",a.playerType);x$.M.P.call(this)};
g.h.load=function(){x$.M.load.call(this);this.g.show();g.T(this.b).ba&&.01>Math.random()&&this.log({trailerEndscreenShow:1})};
g.h.log=function(a){g.Mu(this.b,"end",a)};
g.h.unload=function(){x$.M.unload.call(this);this.g.destroy()};
g.h.AB=function(a){this.Lt()&&(this.g.N||this.g.create(),"load"==a.getId()&&this.load())};
g.h.BB=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.Xr=function(){var a=this.b;g.gq(a.app,"endscreen",a.playerType);var a=Math.max(1E3*(this.b.getVideoData().lengthSeconds-10),0),a=new g.cq(a,0x8000000000000,{id:"preload",namespace:"endscreen"}),b=new g.cq(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});this.b.sb([a,b])};g.da("yt.player.modules.EndScreenModule",x$,void 0);})(_yt_player);
