var _yt_www={};(function(g){var window=this;var baa,caa,Aa,Za,$a,kaa,eb,fb,laa,nb,maa,ub,Gb,Wb,bc,dc,Gc,xaa,yaa,waa,md,zaa,wd,Dd,Fd,Gd,Id,Kd,Caa,Nd,Ad,Ld,Md,xd,Cd,Hd,Ed,Od,Eaa,ae,de,ge,ie,qe,re,Le,Me,Jaa,Ue,Ve,Kaa,Ye,bf,$e,Ze,Laa,ef,ff,jf,lf,mf,nf,qf,tf,sf,pf,rf,uf,gf,kf,Raa,vf,wf,Saa,Taa,Cf,Ef,Gf,Kf,Jf,Lf,Nf,Uaa,Vaa,Waa,Sf,Wf,Xf,Yf,ag,bg,cg,bba,cba,Tf,Vf,Rf,aba,Uf,fg,gg,pa,aaa;g.ba=function(a){return function(){return g.aa[a].apply(this,arguments)}};
g.ca=function(a){return void 0!==a};
g.l=function(a,b,c){a=a.split(".");c=c||g.da;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&g.ca(b)?c[d]=b:c[d]?c=c[d]:c=c[d]={}};
g.m=function(a,b){for(var c=a.split("."),d=b||g.da,e;e=c.shift();)if(null!=d[e])d=d[e];else return null;return d};
g.ea=function(){};
g.fa=function(a){a.getInstance=function(){return a.Cc?a.Cc:a.Cc=new a}};
g.ga=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};
g.ha=function(a){return"array"==g.ga(a)};
g.ka=function(a){var b=g.ga(a);return"array"==b||"object"==b&&"number"==typeof a.length};
g.la=function(a){return"string"==typeof a};
g.ma=function(a){return"number"==typeof a};
g.na=function(a){return"function"==g.ga(a)};
g.oa=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};
g.qa=function(a){return a[pa]||(a[pa]=++aaa)};
baa=function(a,b,c){return a.call.apply(a.bind,arguments)};
caa=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};
g.p=function(a,b,c){g.p=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?baa:caa;return g.p.apply(null,arguments)};
g.ra=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};
g.q=function(a,b){function c(){}
c.prototype=b.prototype;a.N=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.base=function(a,c,h){for(var k=Array(arguments.length-2),n=2;n<arguments.length;n++)k[n-2]=arguments[n];return b.prototype[c].apply(a,k)}};
g.sa=function(a){g.sa[" "](a);return a};
g.ta=function(a,b){return 0==a.lastIndexOf(b,0)};
g.va=function(a){return(0,window.encodeURIComponent)(String(a))};
g.wa=function(a){if(!daa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(eaa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(faa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(gaa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(haa,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(iaa,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(jaa,"&#0;"));return a};
g.xa=function(a,b){return-1!=a.indexOf(b)};
g.ya=function(a){return String(a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")};
g.Ba=function(a,b){for(var c=0,d=(0,g.za)(String(a)).split("."),e=(0,g.za)(String(b)).split("."),h=Math.max(d.length,e.length),k=0;0==c&&k<h;k++){var n=d[k]||"",r=e[k]||"",B=RegExp("(\\d*)(\\D*)","g"),D=RegExp("(\\d*)(\\D*)","g");do{var N=B.exec(n)||["","",""],X=D.exec(r)||["","",""];if(0==N[0].length&&0==X[0].length)break;c=Aa(0==N[1].length?0:(0,window.parseInt)(N[1],10),0==X[1].length?0:(0,window.parseInt)(X[1],10))||Aa(0==N[2].length,0==X[2].length)||Aa(N[2],X[2])}while(0==c)}return c};
Aa=function(a,b){return a<b?-1:a>b?1:0};
g.Ca=function(a){for(var b=0,c=0;c<a.length;++c)b=31*b+a.charCodeAt(c)>>>0;return b};
g.Da=function(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};
g.Ea=function(a){var b=g.la(void 0)?g.ya(void 0):"\\s";return a.replace(new RegExp("(^"+(b?"|["+b+"]+":"")+")([a-z])","g"),function(a,b,e){return b+e.toUpperCase()})};
g.Ga=function(a,b,c){b=g.Fa(a,b,c);return 0>b?null:g.la(a)?a.charAt(b):a[b]};
g.Fa=function(a,b,c){for(var d=a.length,e=g.la(a)?a.split(""):a,h=0;h<d;h++)if(h in e&&b.call(c,e[h],h,a))return h;return-1};
g.Ia=function(a,b){return 0<=(0,g.Ha)(a,b)};
g.La=function(a,b){var c=(0,g.Ha)(a,b),d;(d=0<=c)&&g.Ja(a,c);return d};
g.Ja=function(a,b){return 1==Array.prototype.splice.call(a,b,1).length};
g.Ma=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};
g.Na=function(a){return function(){return a}};
g.Oa=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}};
g.Pa=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};
g.Qa=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};
g.Ra=function(a,b,c){for(var d in a)if(b.call(c,a[d],d,a))return d};
g.Sa=function(a,b){b in a&&delete a[b]};
g.Ta=function(a,b,c){if(null!==a&&b in a)throw Error('The object already contains the key "'+b+'"');a[b]=c};
g.Ua=function(a){var b={},c;for(c in a)b[c]=a[c];return b};
g.Wa=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var h=0;h<Va.length;h++)c=Va[h],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
g.Ya=function(a){return g.xa(g.Xa,a)};
Za=function(){return g.Ya("Opera")||g.Ya("OPR")};
$a=function(){return(g.Ya("Chrome")||g.Ya("CriOS"))&&!Za()&&!g.Ya("Edge")};
g.bb=function(a){g.da.setTimeout(function(){throw a;},0)};
kaa=function(){var a=g.da.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!g.Ya("Presto")&&(a=function(){var a=window.document.createElement("IFRAME");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,g.p)(function(a){if(("*"==
d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);
b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});
if("undefined"!==typeof a&&!g.Ya("Trident")&&!g.Ya("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(g.ca(c.next)){c=c.next;var a=c.Np;c.Np=null;a()}};
return function(a){d.next={Np:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("SCRIPT")?function(a){var b=window.document.createElement("SCRIPT");
b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};
window.document.documentElement.appendChild(b)}:function(a){g.da.setTimeout(a,0)}};
g.cb=function(a,b,c){this.F=c;this.B=a;this.D=b;this.C=0;this.A=null};
g.db=function(a,b){a.D(b);a.C<a.F&&(a.C++,b.next=a.A,a.A=b)};
eb=function(){this.C=this.A=null};
fb=function(){this.next=this.scope=this.Ee=null};
g.lb=function(a,b){gb||laa();ib||(gb(),ib=!0);var c=jb,d=kb.get();d.set(a,b);c.C?c.C.next=d:c.A=d;c.C=d};
laa=function(){if(g.da.Promise&&g.da.Promise.resolve){var a=g.da.Promise.resolve(void 0);gb=function(){a.then(nb)}}else gb=function(){var a=nb;
!g.na(g.da.setImmediate)||g.da.Window&&g.da.Window.prototype&&!g.Ya("Edge")&&g.da.Window.prototype.setImmediate==g.da.setImmediate?(ob||(ob=kaa()),ob(a)):g.da.setImmediate(a)}};
nb=function(){for(var a=null;a=jb.remove();){try{a.Ee.call(a.scope)}catch(b){g.bb(b)}g.db(kb,a)}ib=!1};
g.pb=function(){this.Gd=this.Gd;this.Ib=this.Ib};
g.sb=function(a,b){g.qb(a,g.ra(g.rb,b))};
g.qb=function(a,b){a.Gd?b.call(void 0):(a.Ib||(a.Ib=[]),a.Ib.push(g.ca(void 0)?(0,g.p)(b,void 0):b))};
g.rb=function(a){a&&"function"==typeof a.dispose&&a.dispose()};
g.tb=function(a){g.pb.call(this);this.D=1;this.C=[];this.B=0;this.A=[];this.Ed={};this.F=!!a};
maa=function(a,b,c){g.lb(function(){a.apply(b,c)})};
g.wb=function(a){ub(g.vb,arguments)};
g.t=function(a,b){return a in g.vb?g.vb[a]:b};
g.yb=function(a,b){g.na(a)&&(a=g.xb(a));return window.setTimeout(a,b)};
g.zb=function(a,b){g.na(a)&&(a=g.xb(a));return window.setInterval(a,b)};
g.Ab=function(a){window.clearTimeout(a)};
g.Bb=function(a){window.clearInterval(a)};
g.xb=function(a){return a&&window.yterr?function(){try{return a.apply(this,arguments)}catch(b){throw g.Cb(b),b;}}:a};
g.Cb=function(a,b){var c=g.m("yt.logging.errors.log");c?c(a,b):(c=g.t("ERRORS",[]),c.push([a,b]),g.wb("ERRORS",c))};
g.Eb=function(a){return a in g.Db};
g.Fb=function(a,b,c){var d=b||{};if(a=a in g.Db?g.Db[a]:c)for(var e in d)a=a.replace(new RegExp("\\$"+e,"gi"),function(){return d[e]});
return a};
ub=function(a,b){if(1<b.length){var c=b[0];a[c]=b[1]}else{var d=b[0];for(c in d)a[c]=d[c]}};
g.Lb=function(a,b,c){var d=Gb();if(d){var e=d.subscribe(a,function(){if(!Hb||Hb!=e){var d=arguments,k=function(){Ib[e]&&b.apply(c||window,d)};
try{Jb[a]?k():g.yb(k,0)}catch(n){g.Cb(n)}}},c);
Ib[e]=!0;Kb[a]||(Kb[a]=[]);Kb[a].push(e);return e}return 0};
g.Mb=function(a){var b=Gb();b&&("number"==typeof a?a=[a]:"string"==typeof a&&(a=[(0,window.parseInt)(a,10)]),(0,g.u)(a,function(a){b.unsubscribeByKey(a);delete Ib[a]}))};
g.v=function(a,b){var c=Gb();return c?c.publish.apply(c,arguments):!1};
g.Nb=function(a,b){Jb[a]=!0;var c=Gb(),c=c?c.publish.apply(c,arguments):!1;Jb[a]=!1;return c};
Gb=function(){return g.m("yt.pubsub.instance_")};
g.Ob=function(){return!!g.m("yt.scheduler.instance")};
g.Pb=function(a,b){(0,window.isNaN)(b)&&(b=void 0);var c=g.m("yt.scheduler.instance.addJob");return c?c(a,0,b):void 0===b?(a(),window.NaN):g.yb(a,b||0)};
g.Qb=function(a,b){return g.Pb(a,b)};
g.Rb=function(a){if(!(0,window.isNaN)(a)){var b=g.m("yt.scheduler.instance.cancelJob");b?b(a):g.Ab(a)}};
g.Sb=function(a){for(var b=0,c=a.length;b<c;b++)g.Rb(a[b])};
g.Tb=function(a,b,c,d,e){this.name=a;this.deps=b||[];this.page=c||"";this.G=d?g.xb(d):null;this.F=e?g.xb(e):null;this.D=[];this.A=this.C=0};
g.Ub=function(a){g.Rb(a.C);a.C=g.Qb((0,g.p)(a.init,a))};
g.Xb=function(a){a.name in Vb&&Wb(a.name);Vb[a.name]={reqs:[],disable:(0,g.p)(a.disable,a)};(0,g.u)(a.deps,function(b){if(!(b in Vb))throw Error("Module "+b+" required by "+a.name);Vb[b].reqs.push(a.name)});
a.enable()};
Wb=function(a){if(a in Vb){var b=Vb[a];(0,g.u)(b.reqs,function(a){Wb(a)});
try{b.disable()}catch(c){}delete Vb[a]}};
g.Zb=function(){this.A="";this.C=Yb};
g.$b=function(a){return a instanceof g.Zb&&a.constructor===g.Zb&&a.C===Yb?a.A:"type_error:Const"};
bc=function(){this.A="";this.C=ac};
g.cc=function(a){if(a instanceof bc&&a.constructor===bc&&a.C===ac)return a.A;g.ga(a);return"type_error:SafeStyle"};
dc=function(a){var b=new bc;b.A=a;return b};
g.ec=function(a){var b="",c;for(c in a){if(!/^[-_a-zA-Z0-9]+$/.test(c))throw Error("Name allows only [-_a-zA-Z0-9], got: "+c);var d=a[c];if(null!=d){if(d instanceof g.Zb)d=g.$b(d);else if(naa.test(d)){for(var e=!0,h=!0,k=0;k<d.length;k++){var n=d.charAt(k);"'"==n&&h?e=!e:'"'==n&&e&&(h=!h)}e&&h||(d="zClosurez")}else d="zClosurez";b+=c+":"+d+";"}}return b?dc(b):oaa};
g.gc=function(){this.A="";this.C=fc};
g.hc=function(a){if(a instanceof g.gc&&a.constructor===g.gc&&a.C===fc)return a.A;g.ga(a);return"type_error:SafeUrl"};
g.jc=function(a){if(a instanceof g.gc)return a;a=a.Yf?a.$e():String(a);paa.test(a)||(a="about:invalid#zClosurez");return g.ic(a)};
g.ic=function(a){var b=new g.gc;b.A=a;return b};
g.lc=function(){this.A="";this.C=kc};
g.mc=function(a){if(a instanceof g.lc&&a.constructor===g.lc&&a.C===kc)return a.A;g.ga(a);return"type_error:TrustedResourceUrl"};
g.oc=function(){this.A="";this.B=nc;this.C=null};
g.pc=function(a){if(a instanceof g.oc&&a.constructor===g.oc&&a.B===nc)return a.A;g.ga(a);return"type_error:SafeHtml"};
g.rc=function(a){if(a instanceof g.oc)return a;var b=null;a.Nm&&(b=a.Gg());a=g.wa(a.Yf?a.$e():String(a));return g.qc(a,b)};
g.uc=function(a,b,c){if(!sc.test(a))throw Error("Invalid tag name <"+a+">.");if(a.toUpperCase()in qaa)throw Error("Tag name <"+a+"> is not allowed for SafeHtml.");return g.tc(a,b,c)};
g.vc=function(a){function b(a){g.ha(a)?(0,g.u)(a,b):(a=g.rc(a),d+=g.pc(a),a=a.Gg(),0==c?c=a:0!=a&&c!=a&&(c=null))}
var c=0,d="";(0,g.u)(arguments,b);return g.qc(d,c)};
g.qc=function(a,b){var c=new g.oc;c.A=a;c.C=b;return c};
g.tc=function(a,b,c){var d=null,e="<"+a;if(b)for(var h in b){if(!sc.test(h))throw Error('Invalid attribute name "'+h+'".');var k=b[h];if(null!=k){var n,r=a;n=h;if(k instanceof g.Zb)k=g.$b(k);else if("style"==n.toLowerCase()){if(!g.oa(k))throw Error('The "style" attribute requires goog.html.SafeStyle or map of style properties, '+typeof k+" given: "+k);k instanceof bc||(k=g.ec(k));k=g.cc(k)}else{if(/^on/i.test(n))throw Error('Attribute "'+n+'" requires goog.string.Const value, "'+k+'" given.');if(n.toLowerCase()in
raa)if(k instanceof g.lc)k=g.mc(k);else if(k instanceof g.gc)k=g.hc(k);else if(g.la(k))k=g.jc(k).$e();else throw Error('Attribute "'+n+'" on tag "'+r+'" requires goog.html.SafeUrl, goog.string.Const, or string, value "'+k+'" given.');}k.Yf&&(k=k.$e());n=n+'="'+g.wa(String(k))+'"';e=e+(" "+n)}}null!=c?g.ha(c)||(c=[c]):c=[];!0===saa[a.toLowerCase()]?e+=">":(d=g.vc(c),e+=">"+g.pc(d)+"</"+a+">",d=d.Gg());(a=b&&b.dir)&&(/^(ltr|rtl|auto)$/i.test(a)?d=0:d=null);return g.qc(e,d)};
g.wc=function(a,b){a.innerHTML=g.pc(b)};
g.xc=function(a,b){var c;c=b instanceof g.gc?b:g.jc(b);a.href=g.hc(c)};
g.w=function(a,b){return a?a.dataset?a.dataset[g.yc(b)]:a.getAttribute("data-"+b):null};
g.zc=function(a,b){return a?a.dataset?g.yc(b)in a.dataset:a.hasAttribute?!!a.hasAttribute("data-"+b):!!a.getAttribute("data-"+b):!1};
g.yc=function(a){return Ac[a]||(Ac[a]=String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()}))};
g.Cc=function(a,b){var c=g.Bc(a);window.spf.script.load(a,c,b)};
g.Dc=function(a,b){var c=g.Bc(a);window.spf.script.ignore(c,b)};
g.Bc=function(a){var b="";if(a){var c=a.indexOf("jsbin/"),d=a.lastIndexOf(".js"),e=c+6;-1<c&&-1<d&&d>e&&(b=a.substring(e,d),b=b.replace(taa,""),b=b.replace(uaa,""),b=b.replace("debug-",""),b=b.replace("tracing-",""))}return b};
g.Ec=function(a,b){this.x=g.ca(a)?a:0;this.y=g.ca(b)?b:0};
g.Fc=function(){return g.Ya("iPhone")&&!g.Ya("iPod")&&!g.Ya("iPad")};
Gc=function(){var a=g.da.document;return a?a.documentMode:void 0};
g.Jc=function(a){return Hc[a]||(Hc[a]=0<=g.Ba(g.Ic,a))};
g.Lc=function(a){return Number(g.Kc)>=a};
g.x=function(a){return g.la(a)?window.document.getElementById(a):a};
g.Mc=function(a){return g.la(a)?window.document.getElementById(a):a};
g.y=function(a,b){var c=b||window.document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:c.querySelectorAll&&c.querySelector?d=c.querySelector("."+a):d=g.Nc(window.document,"*",a,b)[0];return d||null};
g.Nc=function(a,b,c,d){a=d||a;b=b&&"*"!=b?b.toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={};for(var e=0,h=0,k;k=a[h];h++)b==k.nodeName&&(d[e++]=k);d.length=e;return d}return a}a=a.getElementsByTagName(b||"*");if(c){d={};for(h=e=0;k=a[h];h++)b=k.className,"function"==typeof b.split&&g.Ia(b.split(/\s+/),c)&&(d[e++]=k);d.length=e;return d}return a};
g.Pc=function(a,b){g.Pa(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:Oc.hasOwnProperty(d)?a.setAttribute(Oc[d],b):g.ta(d,"aria-")||g.ta(d,"data-")?a.setAttribute(d,b):a[d]=b})};
g.Rc=function(a){var b=g.Qc(a);a=a.parentWindow||a.defaultView;return g.z&&g.Jc("10")&&a.pageYOffset!=b.scrollTop?new g.Ec(b.scrollLeft,b.scrollTop):new g.Ec(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};
g.Qc=function(a){return a.scrollingElement?a.scrollingElement:!g.Sc&&g.Tc(a)?a.documentElement:a.body||a.documentElement};
g.Vc=function(a,b,c){return g.Uc(window.document,arguments)};
g.Uc=function(a,b){var c=b[0],d=b[1];if(!vaa&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',g.wa(d.name),'"');if(d.type){c.push(' type="',g.wa(d.type),'"');var e={};g.Wa(e,d);delete e.type;d=e}c.push(">");c=c.join("")}c=a.createElement(c);d&&(g.la(d)?c.className=d:g.ha(d)?c.className=d.join(" "):g.Pc(c,d));2<b.length&&g.Wc(a,c,b,2);return c};
g.Wc=function(a,b,c,d){function e(c){c&&b.appendChild(g.la(c)?a.createTextNode(c):c)}
for(;d<c.length;d++){var h=c[d];!g.ka(h)||g.oa(h)&&0<h.nodeType?e(h):(0,g.u)(waa(h)?g.Ma(h):h,e)}};
g.Tc=function(a){return"CSS1Compat"==a.compatMode};
g.Xc=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};
g.Yc=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};
g.$c=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};
xaa=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};
yaa=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};
g.ad=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};
waa=function(a){if(a&&"number"==typeof a.length){if(g.oa(a))return"function"==typeof a.item||"string"==typeof a.item;if(g.na(a))return"function"==typeof a.item}return!1};
g.bd=function(a,b,c,d){c||(a=a.parentNode);for(c=0;a&&(null==d||c<=d);){if(b(a))return a;a=a.parentNode;c++}return null};
g.cd=function(a,b,c,d,e,h,k){var n="";a&&(n+=a+":");c&&(n+="//",b&&(n+=b+"@"),n+=c,d&&(n+=":"+d));e&&(n+=e);h&&(n+="?"+h);k&&(n+="#"+k);return n};
g.dd=function(a){return a?(0,window.decodeURI)(a):a};
g.fd=function(a,b){return b.match(g.ed)[a]||null};
g.hd=function(a){return g.dd(g.fd(3,a))};
g.id=function(a){a=a.match(g.ed);return g.cd(null,null,null,null,a[5],a[6],a[7])};
g.jd=function(a){var b=a.indexOf("#");return 0>b?a:a.substr(0,b)};
g.kd=function(a){if(a[1]){var b=a[0],c=b.indexOf("#");0<=c&&(a.push(b.substr(c)),a[0]=b=b.substr(0,c));c=b.indexOf("?");0>c?a[1]="?":c==b.length-1&&(a[1]=void 0)}return a.join("")};
g.ld=function(a,b,c){if(g.ha(b))for(var d=0;d<b.length;d++)g.ld(a,String(b[d]),c);else null!=b&&c.push("&",a,""===b?"":"=",g.va(b))};
md=function(a,b){for(var c in b)g.ld(c,b[c],a);return a};
g.nd=function(a){a=md([],a);a[0]="";return a.join("")};
g.od=function(a,b){return g.kd(md([a],b))};
g.pd=function(a,b,c){a&&(c&&(c=g.Xa,c=!(c&&0<=c.toLowerCase().indexOf("cobalt"))),c?a&&(a=g.Vc("iframe",{src:'javascript:"data:text/html,<body><img src=\\"'+a+'\\"></body>"',style:"display:none"}),g.ad(a).body.appendChild(a)):zaa(a,b))};
g.qd=function(a){try{window.navigator&&window.navigator.sendBeacon&&window.navigator.sendBeacon(a,"")||g.pd(a,void 0)}catch(b){g.pd(a,void 0)}};
zaa=function(a,b){var c=new window.Image,d=""+Aaa++;rd[d]=c;c.onload=c.onerror=function(){b&&rd[d]&&b();delete rd[d]};
c.src=a};
g.sd=function(a,b){this.version=a;this.args=b};
g.td=function(a,b){this.topic=a;this.Gf=b};
g.vd=function(a,b){var c=g.ud();return c?c.publish.call(c,a.toString(),a,b):!1};
g.ud=function(){return g.m("yt.pubsub2.instance_")};
wd=function(a){g.sd.call(this,1,arguments)};
g.Bd=function(a,b,c){xd(c)[a]=b||(0,g.yd)();b||zd(a);Ad(!1,c)};
Dd=function(a,b){Cd(void 0).yt_sts=a;g.Bd("_start",b,void 0)};
Fd=function(a){Ed(a);Baa();g.l("yt.timing.pingSent_",!1,void 0)};
Gd=function(a){a=xd(a);if(a.aft)return a.aft;for(var b=g.t("TIMING_AFT_KEYS",["ol"]),c=b.length,d=0;d<c;d++){var e=a[b[d]];if(e)return e}return window.NaN};
Id=function(a,b){var c=b||Hd(void 0).span,d;d=a.redirectEnd-a.redirectStart;0<d&&(c.rtime_=d);d=a.domainLookupEnd-a.domainLookupStart;0<d&&(c.dns_=d);d=a.connectEnd-a.connectStart;0<d&&(c.tcp_=d);d=a.connectEnd-a.secureConnectionStart;a.secureConnectionStart>=a.navigationStart&&0<d&&(c.stcp_=d);d=a.responseStart-a.requestStart;0<d&&(c.req_=d);d=a.responseEnd-a.responseStart;0<d&&(c.rcv_=d)};
Kd=function(a){return Math.round(Jd.timing.navigationStart+a)};
Caa=function(a){var b=window.location.protocol,c=Jd.getEntriesByType("resource"),d=c.filter(function(a){return 0==a.name.indexOf(b+"//fonts.googleapis.com/css?family=")})[0],c=c.filter(function(a){return 0==a.name.indexOf(b+"//fonts.gstatic.com/s/")}).reduce(function(a,b){return b.duration>a.duration?b:a},{duration:0});
d&&0<d.startTime&&0<d.responseEnd&&(a.wfcs=Kd(d.startTime),a.wfce=Kd(d.responseEnd));c&&0<c.startTime&&0<c.responseEnd&&(a.wffs=Kd(c.startTime),a.wffe=Kd(c.responseEnd))};
Nd=function(a){var b=xd(a),c=Hd(a).span,d=Cd(a),e=g.m("yt.timing.reportbuilder_");if(e){if(e=e(b,c,d,a))Ld(e),Fd(a)}else{var h=g.t("CSI_SERVICE_NAME","youtube"),e={v:2,s:h,action:g.t("TIMING_ACTION",void 0)};if(Jd.now&&Jd.timing){var k=Jd.timing.navigationStart+Jd.now(),k=Math.round((0,g.yd)()-k);d.yt_hrd=k}var k=g.t("TIMING_INFO",{}),n;for(n in k)d[n]=k[n];n=d.srt;delete d.srt;var r;n||0===n||(r=Jd.timing||{},n=Math.max(0,r.responseStart-r.navigationStart),(0,window.isNaN)(n)&&d.pt&&(n=d.pt));if(n||
0===n)d.srt=n;d.h5jse&&(k=window.location.protocol+g.m("ytplayer.config.assets.js"),(k=Jd.getEntriesByName?Jd.getEntriesByName(k)[0]:null)?d.h5jse=Math.round(d.h5jse-k.responseEnd):delete d.h5jse);b.aft=Gd(a);k=b._start;if("cold"==d.yt_lt){r||(r=Jd.timing||{});var B;a:if(B=r,B.msFirstPaint)B=Math.max(0,B.msFirstPaint);else{var D=window.chrome;if(D&&(D=D.loadTimes,g.na(D))){var D=D(),N=1E3*Math.min(D.requestTime||window.Infinity,D.startLoadTime||window.Infinity),N=window.Infinity===N?0:B.navigationStart-
N;B=Math.max(0,Math.round(1E3*D.firstPaintTime+N)||0);break a}B=0}0<B&&B>k&&(b.fpt=B);Id(r,c);Jd.getEntriesByType&&Caa(b)}D=xd(a);r=D.pbr;B=D.vc;D=D.pbs;r&&B&&D&&r<B&&B<D&&1==Cd(a).yt_vis&&"youtube"==h&&(Cd(a).yt_lt="hot_bg",h=b.vc,r=b.pbs,delete b.aft,c.aft=Math.round(r-h));(h=g.t("PREVIOUS_ACTION"))&&(d.pa=h);d.p=g.t("CLIENT_PROTOCOL")||"unknown";d.t=g.t("CLIENT_TRANSPORT")||"unknown";window.navigator&&window.navigator.sendBeacon&&(d.ba=1);for(var X in d)"_"!=X.charAt(0)&&(e[X]=d[X]);b.ps=(0,g.yd)();
d={};X=[];for(var ia in b)"_"!=ia.charAt(0)&&(B=Math.round(b[ia]-k),d[ia]=B,X.push(ia+"."+B));e.rt=X.join(",");b=e;ia=[];for(var ua in c)"_"!=ua.charAt(0)&&ia.push(ua+"."+c[ua]);b.it=ia.join(",");(ua=g.m("ytdebug.logTiming"))&&ua(e,d,c);Fd(a);g.t("EXP_DEFER_CSI_PING")?(Md(),g.l("yt.timing.deferredPingArgs_",e,void 0),a=g.yb(Md,0),g.l("yt.timing.deferredPingTimer_",a,void 0)):Ld(e);g.vd(Daa,new wd(d.aft+(n||0)))}};
Ad=function(a,b){var c=g.t("TIMING_ACTION",void 0),d=xd(b);if(g.m("yt.timing.ready_")&&c&&d._start&&Gd(b)){var c=!0,e=g.t("TIMING_WAIT",[]);if(!a&&e.length)for(var h=0,k=e.length;h<k;++h)if(!(e[h]in d)){c=!1;break}(c||b)&&Nd(b)}};
Ld=function(a){if(g.t("DEBUG_CSI_DATA")){var b=g.m("yt.timing.csiData");b||(b=[],g.l("yt.timing.csiData",b,void 0));b.push({page:window.location.href,time:new Date,args:a})}g.t("EXP_DEFER_CSI_PING")&&(g.Ab(g.m("yt.timing.deferredPingTimer_")),g.l("yt.timing.deferredPingArgs_",null,void 0));var c="https:"==window.location.protocol?"https://gg.google.com/csi":"http://csi.gstatic.com/csi",c=g.t("CSI_LOG_WITH_YT")?"/csi_204":c,b="",d;for(d in a)b+="&"+d+"="+a[d];a=c+"?"+b.substring(1);b=g.t("DOUBLE_LOG_CSI")?
"/csi_204?"+b.substring(1):null;window.navigator&&window.navigator.sendBeacon?(g.qd(a),b&&g.qd(b)):(g.pd(a),b&&g.pd(b));g.l("yt.timing.pingSent_",!0,void 0)};
Md=function(a){if(g.t("EXP_DEFER_CSI_PING")){var b=g.m("yt.timing.deferredPingArgs_");b&&(a&&(b.yt_fss=a),Ld(b))}};
xd=function(a){return Hd(a).tick};
Cd=function(a){return Hd(a).info};
Hd=function(a){return g.m("ytcsi."+(a||"")+"data_")||Ed(a)};
Ed=function(a){var b={tick:{},span:{},info:{}};g.l("ytcsi."+(a||"")+"data_",b,void 0);return b};
Od=function(a){g.m("yt.timing.pingSent_")||(g.Bd("aa"),Cd(void 0).ap=1,Cd(void 0).yt_fss=a,Nd())};
Eaa=function(a){a=g.Pd(a);return g.Qd(a)||(null===a?!1:"google"==a[1]?!0:"google"==a[2]?"au"==a[0]&&"com"==a[1]?!0:"uk"==a[0]&&"co"==a[1]?!0:!1:!1)};
g.Qd=function(a){return null===a?!1:"com"==a[0]&&a[1].match(/^youtube(?:-nocookie)?$/)?!0:!1};
g.Pd=function(a){a=g.hd(a);return null===a?null:a.split(".").reverse()};
g.Rd=function(a,b){g.pd("/gen_204?"+a,b)};
g.Sd=function(a){if(a.classList)return a.classList;a=a.className;return g.la(a)&&a.match(/\S+/g)||[]};
g.A=function(a,b){return a.classList?a.classList.contains(b):g.Ia(g.Sd(a),b)};
g.C=function(a,b){a.classList?a.classList.add(b):g.A(a,b)||(a.className+=0<a.className.length?" "+b:b)};
g.E=function(a,b){a.classList?a.classList.remove(b):g.A(a,b)&&(a.className=(0,g.Td)(g.Sd(a),function(a){return a!=b}).join(" "))};
g.Ud=function(a,b,c){c?g.C(a,b):g.E(a,b)};
g.Vd=function(a){var b=a.cloneNode(!1);"TR"==b.tagName||"SELECT"==b.tagName?(0,g.u)(a.childNodes,function(a){b.appendChild(g.Vd(a))}):b.innerHTML=a.innerHTML;
return b};
g.Wd=function(a){this.type="";this.state=this.source=this.data=this.currentTarget=this.relatedTarget=this.target=null;this.charCode=this.keyCode=0;this.shiftKey=this.ctrlKey=this.altKey=!1;this.rotation=this.clientY=this.clientX=0;this.scale=1;this.changedTouches=this.touches=null;if(a=a||window.event){this.event=a;for(var b in a)b in Faa||(this[b]=a[b]);this.scale=a.scale;this.rotation=a.rotation;(b=a.target||a.srcElement)&&3==b.nodeType&&(b=b.parentNode);this.target=b;if(b=a.relatedTarget)try{b=
b.nodeName?b:null}catch(c){b=null}else"mouseover"==this.type?b=a.fromElement:"mouseout"==this.type&&(b=a.toElement);this.relatedTarget=b;this.clientX=void 0!=a.clientX?a.clientX:a.pageX;this.clientY=void 0!=a.clientY?a.clientY:a.pageY;this.keyCode=a.keyCode?a.keyCode:a.which;this.charCode=a.charCode||("keypress"==this.type?this.keyCode:0);this.altKey=a.altKey;this.ctrlKey=a.ctrlKey;this.shiftKey=a.shiftKey;this.Cn=a.pageX;this.Dn=a.pageY}};
g.Yd=function(a,b,c,d){return g.Ra(g.Xd,function(e){return e[0]==a&&e[1]==b&&e[2]==c&&e[4]==!!d})};
g.F=function(a,b,c,d){if(!a||!a.addEventListener&&!a.attachEvent)return"";d=!!d;var e=g.Yd(a,b,c,d);if(e)return e;var e=++Zd.count+"",h=!("mouseenter"!=b&&"mouseleave"!=b||!a.addEventListener||"onmouseenter"in window.document),k;k=h?function(d){d=new g.Wd(d);if(!g.bd(d.relatedTarget,function(b){return b==a},!0))return d.currentTarget=a,d.type=b,c.call(a,d)}:function(b){b=new g.Wd(b);
b.currentTarget=a;return c.call(a,b)};
k=g.xb(k);g.Xd[e]=[a,b,c,k,d];a.addEventListener?"mouseenter"==b&&h?a.addEventListener("mouseover",k,d):"mouseleave"==b&&h?a.addEventListener("mouseout",k,d):"mousewheel"==b&&"MozBoxSizing"in window.document.documentElement.style?a.addEventListener("MozMousePixelScroll",k,d):a.addEventListener(b,k,d):a.attachEvent("on"+b,k);return e};
g.$d=function(a){a=a||window.event;a.returnValue=!1;a.preventDefault&&a.preventDefault()};
g.be=function(){if(null==g.m("_lact",window)){var a=(0,window.parseInt)(g.t("LACT"),10),a=(0,window.isFinite)(a)?(0,g.yd)()-Math.max(a,0):-1;g.l("_lact",a,window);-1==a&&ae();g.F(window.document,"keydown",ae);g.F(window.document,"keyup",ae);g.F(window.document,"mousedown",ae);g.F(window.document,"mouseup",ae);g.Lb("page-mouse",ae);g.Lb("page-scroll",ae);g.Lb("page-resize",ae)}};
ae=function(){null==g.m("_lact",window)&&(g.be(),g.m("_lact",window));var a=(0,g.yd)();g.l("_lact",a,window);g.v("USER_ACTIVE")};
g.ce=function(){var a=g.m("_lact",window);return null==a?-1:Math.max((0,g.yd)()-a,0)};
de=function(a){a=a||{};this.url=a.url||"";this.urlV9As2=a.url_v9as2||"";this.args=a.args||g.Ua(Gaa);this.assets=a.assets||{};this.attrs=a.attrs||g.Ua(Haa);this.params=a.params||g.Ua(Iaa);this.minVersion=a.min_version||"8.0.0";this.fallback=a.fallback||null;this.fallbackMessage=a.fallbackMessage||null;this.html5=!!a.html5;this.disable=a.disable||{};this.loaded=!!a.loaded;this.messages=a.messages||{}};
g.ee=function(a){a instanceof de||(a=new de(a));return a};
ge=function(){return null!=g.fe};
g.he=function(){return g.fe?g.fe.invoke():null};
ie=function(){return(0,window.parseInt)(g.t("DCLKSTAT",0),10)};
g.je=function(a,b,c){this.A=a;this.B=b;this.C=c};
g.ke=function(a){this.A=a};
g.me=function(a){a=(a.A.cookie||"").split(g.le);for(var b=[],c=[],d,e,h=0;e=a[h];h++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};
g.oe=function(a,b,c,d){g.ne.set(""+a,b,c,"/",d||"youtube.com")};
g.pe=function(a,b){return g.ne.get(""+a,b)};
g.se=function(a,b,c){var d=g.t("VALID_SESSION_TEMPDATA_DOMAINS",[]),e=g.hd(window.location.href);e&&d.push(e);e=g.hd(a);if(g.Ia(d,e)||!e&&g.ta(a,"/"))if(a=g.id(a),a=g.jd(a))c?(c=(0,window.parseInt)(c,10),(0,window.isFinite)(c)&&0<c&&(qe(a,b,c),re(b))):(qe(a,b),re(b))};
qe=function(a,b,c){var d=g.t("ST_BASE36",!0),e;e=g.t("ST_SHORT",!0)?"ST-":"s_tempdata-";a=e=d?e+g.Ca(a).toString(36):e+g.Ca(a);c=c||5;b=b?g.nd(b):"";g.oe(a,b,c)};
re=function(a){if(a){a=a.itct||a.ved;var b=g.m("yt.logging.screenreporter.storeParentElement");a&&b&&b(new g.je(a))}};
g.te=function(a,b,c){c=c||"";g.xc(window.location,g.od(a,b||{})+c)};
g.ue=function(a,b){b&&g.se(a,b);(window.ytspf||{}).enabled?window.spf.navigate(a):g.te(a)};
g.ve=function(a,b,c){var d=g.t("EVENT_ID");d&&(b||(b={}),b.ei||(b.ei=d));b&&g.se(a,b);if(c)return!1;g.ue(a);return!0};
g.ye=function(){return g.Sc?"Webkit":g.we?"Moz":g.z?"ms":g.xe?"O":null};
g.ze=function(){return g.Sc?"-webkit":g.we?"-moz":g.z?"-ms":g.xe?"-o":null};
g.Ae=function(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d};
g.Be=function(a,b){return a&&b?b instanceof g.Ae?b.left>=a.left&&b.right<=a.right&&b.top>=a.top&&b.bottom<=a.bottom:b.x>=a.left&&b.x<=a.right&&b.y>=a.top&&b.y<=a.bottom:!1};
g.De=function(a,b){var c=Ce[b];if(!c){var d=g.Da(b),c=d;void 0===a.style[d]&&(d=g.ye()+g.Ea(d),void 0!==a.style[d]&&(c=d));Ce[b]=c}return c};
g.Ee=function(a,b){var c=a.style[g.Da(b)];return"undefined"!==typeof c?c:a.style[g.De(a,b)]||""};
g.Fe=function(a,b){"number"==typeof a&&(a=(b?Math.round(a):a)+"px");return a};
g.Ge=function(a,b){a.style.height=g.Fe(b,!0)};
g.He=function(a,b){a.style.width=g.Fe(b,!0)};
g.Ie=function(a,b){a.style.display=b?"":"none"};
g.Ke=function(){var a=g.pe("PREF");if(a)for(var a=(0,window.unescape)(a).split("&"),b=0;b<a.length;b++){var c=a[b].split("="),d=c[0];(c=c[1])&&(g.Je[d]=c.toString())}};
Le=function(a){if(/^f([1-9][0-9]*)$/.test(a))throw"ExpectedRegexMatch: "+a;};
Me=function(a){if(!/^\w+$/.test(a))throw"ExpectedRegexMismatch: "+a;};
g.Ne=function(a){a=void 0!==g.Je[a]?g.Je[a].toString():null;return null!=a&&/^[A-Fa-f0-9]+$/.test(a)?(0,window.parseInt)(a,16):null};
g.Oe=function(a,b){return!!((g.Ne("f"+(Math.floor(b/31)+1))||0)&1<<b%31)};
g.Pe=function(a,b){(a=g.x(a))&&a.style&&(g.Ie(a,b),g.Ud(a,"hid",!b))};
g.Qe=function(a){return(a=g.x(a))?!("none"==a.style.display||g.A(a,"hid")):!1};
Jaa=function(a){if(a=g.x(a))g.Qe(a)?(g.Ie(a,!1),g.C(a,"hid")):(g.Ie(a,!0),g.E(a,"hid"))};
g.G=function(a){(0,g.u)(arguments,function(a){!g.ka(a)||a instanceof window.Element?g.Pe(a,!0):(0,g.u)(a,function(a){g.G(a)})})};
g.H=function(a){(0,g.u)(arguments,function(a){!g.ka(a)||a instanceof window.Element?g.Pe(a,!1):(0,g.u)(a,function(a){g.H(a)})})};
g.Re=function(a){(0,g.u)(arguments,function(a){g.ka(a)?(0,g.u)(a,function(a){g.Re(a)}):Jaa(a)})};
g.Te=function(){this.A=this.minor=this.major=0;this.C="";var a=g.m("window.navigator.plugins"),b=g.m("window.navigator.mimeTypes"),a=a&&a["Shockwave Flash"],b=b&&b["application/x-shockwave-flash"],b=a&&b&&b.enabledPlugin&&a.description||"";if(a=b){var c=a.indexOf("Shockwave Flash");0<=c&&(a=a.substr(c+15));for(var c=a.split(" "),d="",a="",e=0,h=c.length;e<h;e++)if(d)if(a)break;else a=c[e];else d=c[e];d=d.split(".");c=(0,window.parseInt)(d[0],10)||0;d=(0,window.parseInt)(d[1],10)||0;e=0;if("r"==a.charAt(0)||
"d"==a.charAt(0))e=(0,window.parseInt)(a.substr(1),10)||0;a=[c,d,e]}else a=[0,0,0];this.C=b;b=a;this.major=b[0];this.minor=b[1];this.A=b[2];if(0>=this.major){var k,n,r,B;if(g.Se)try{k=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(D){k=null}else r=window.document.body,B=window.document.createElement("object"),B.setAttribute("type","application/x-shockwave-flash"),k=r.appendChild(B);if(k&&"GetVariable"in k)try{n=k.GetVariable("$version")}catch(D){n=""}r&&B&&r.removeChild(B);(k=n||
"")?(k=k.split(" ")[1].split(","),k=[(0,window.parseInt)(k[0],10)||0,(0,window.parseInt)(k[1],10)||0,(0,window.parseInt)(k[2],10)||0]):k=[0,0,0];this.major=k[0];this.minor=k[1];this.A=k[2]}};
Ue=function(a,b,c,d){b="string"==typeof b?b.split("."):[b,c,d];b[0]=(0,window.parseInt)(b[0],10)||0;b[1]=(0,window.parseInt)(b[1],10)||0;b[2]=(0,window.parseInt)(b[2],10)||0;return a.major>b[0]||a.major==b[0]&&a.minor>b[1]||a.major==b[0]&&a.minor==b[1]&&a.A>=b[2]};
Ve=function(a){return-1<a.C.indexOf("Gnash")&&-1==a.C.indexOf("AVM2")||9==a.major&&1==a.minor||9==a.major&&0==a.minor&&1==a.A?!1:9<=a.major};
Kaa=function(a){return g.We?!Ue(a,11,2):g.Xe?!Ue(a,11,3):!Ve(a)};
Ye=function(a,b,c){if(b){a=g.la(a)?g.Mc(a):a;var d=g.Ua(c.attrs);d.tabindex=0;var e=g.Ua(c.params);e.flashvars=g.nd(c.args);if(g.Se){d.classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000";e.movie=b;b=window.document.createElement("object");for(var h in d)b.setAttribute(h,d[h]);for(h in e)d=window.document.createElement("param"),d.setAttribute("name",h),d.setAttribute("value",e[h]),b.appendChild(d)}else{d.type="application/x-shockwave-flash";d.src=b;b=window.document.createElement("embed");b.setAttribute("name",
d.id);for(h in d)b.setAttribute(h,d[h]);for(h in e)b.setAttribute(h,e[h])}e=window.document.createElement("div");e.appendChild(b);a.innerHTML=e.innerHTML}};
g.af=function(a,b){a=g.la(a)?g.Mc(a):a;b=g.ee(b);if(window!=window.top){var c=null;window.document.referrer&&(c=window.document.referrer.substring(0,128));b.args.framer=c}c=g.Te.getInstance();Ue(c,b.minVersion)?(c=Ze(b,c),Ye(a,c,b)):$e(a,b,c)};
bf=function(a,b,c){if(a&&a.attrs&&a.attrs.id){a=g.ee(a);var d=!!b,e=g.x(a.attrs.id),h=e?e.parentNode:null;if(e&&h){if(window!=window.top){var k=null;if(window.document.referrer){var n=window.document.referrer.substring(0,128);Eaa(n)||(k=n)}else k="unknown";k&&(d=!0,a.args.framer=k)}k=g.Te.getInstance();if(Ue(k,a.minVersion)){var n=Ze(a,k),r="";-1<window.navigator.userAgent.indexOf("Sony/COM2")||(r=e.getAttribute("src")||e.movie);(r!=n||d)&&Ye(h,n,a);Kaa(k)&&Laa()}else $e(h,a,k);c&&c()}else g.yb(function(){bf(a,
b,c)},50)}};
$e=function(a,b,c){0==c.major&&b.fallback?b.fallback():0==c.major&&b.fallbackMessage?b.fallbackMessage():a.innerHTML='<div id="flash-upgrade">'+g.Fb("FLASH_UPGRADE",void 0,'You need to upgrade your Adobe Flash Player to watchthis video. <br> <a href="http://get.adobe.com/flashplayer/">Download it from Adobe.</a>')+"</div>"};
Ze=function(a,b){var c;(c=Ve(b)&&a.url)||(c=(-1<window.navigator.userAgent.indexOf("Sony/COM2")&&!Ue(b,9,1,58)?!1:!0)&&a.urlV9As2);return c||a.url};
Laa=function(){var a=g.x("flash10-promo-div"),b=g.Oe(g.Ke.getInstance(),107);a&&!b&&g.G(a)};
g.cf=function(a,b){var c=a.match(Maa);window.spf.style.load(a,c?c[1]:"",b)};
g.df=function(a){g.pb.call(this);this.A=[];this.C=a||this};
ef=function(a,b,c,d){d=g.xb((0,g.p)(d,a.C));b.addEventListener(c,d);a.A.push({target:b,name:c,Yb:d})};
ff=function(a){for(;a.A.length;){var b=a.A.pop();b.target.removeEventListener(b.name,b.Yb)}};
jf=function(a,b){g.pb.call(this);this.R=this.D=a;this.la=b;this.M=!1;this.api={};this.Xa=this.X=null;this.aa=new g.tb;g.sb(this,this.aa);this.B={};this.F=this.ab=this.C=this.tb=this.A=null;this.ga=!1;this.Y=this.G=this.O=this.V=null;this.bb={};this.mc=["onReady"];this.ia=new g.df(this);g.sb(this,this.ia);this.Eb=null;this.Nb=window.NaN;this.qa={};gf(this);this.xe("onDetailedError",(0,g.p)(this.EI,this));this.xe("onTabOrderChange",(0,g.p)(this.uy,this));this.xe("onTabAnnounce",(0,g.p)(this.np,this));
this.xe("WATCH_LATER_VIDEO_ADDED",(0,g.p)(this.II,this));this.xe("WATCH_LATER_VIDEO_REMOVED",(0,g.p)(this.JI,this));g.hf||(this.xe("onMouseWheelCapture",(0,g.p)(this.nI,this)),this.xe("onMouseWheelRelease",(0,g.p)(this.oI,this)));this.xe("onAdAnnounce",(0,g.p)(this.np,this));this.J=new g.df(this);g.sb(this,this.J);this.lb=!1;this.fb=null};
lf=function(a,b){a.tb=b;a.A=b.clone();a.C=a.A.attrs.id||a.C;"video-player"==a.C&&(a.C=a.la,a.A.attrs.id=a.la);a.R.id==a.C&&(a.C+="-player",a.A.attrs.id=a.C);a.A.args.enablejsapi="1";a.A.args.playerapiid=a.la;a.ab||(a.ab=kf(a,a.A.args.jsapicallback||"onYouTubePlayerReady"));a.A.args.jsapicallback=null;var c=a.A.attrs.width;c&&g.He(a.R,Number(c)||c);(c=a.A.attrs.height)&&g.Ge(a.R,Number(c)||c)};
mf=function(a){a.A.loaded||(a.A.loaded=!0,"0"!=a.A.args.autoplay?a.api.loadVideoByPlayerVars(a.A.args):a.api.cueVideoByPlayerVars(a.A.args))};
nf=function(a){if(!g.ca(a.A.disable.flash)){var b=a.A.disable,c;c=Ue(g.Te.getInstance(),a.A.minVersion);b.flash=!c}return!a.A.disable.flash};
qf=function(a){var b;if(!(b=!a.A.html5&&nf(a))){if(!g.ca(a.A.disable.html5)){var c;b=!0;void 0!=a.A.args.deviceHasDisplay&&(b=a.A.args.deviceHasDisplay);if(2.2==of)c=!0;else{a:{var d=b;b=g.m("yt.player.utils.videoElement_");b||(b=window.document.createElement("video"),g.l("yt.player.utils.videoElement_",b,void 0));try{if(b.canPlayType)for(var d=d?Naa:Oaa,e=0;e<d.length;e++)if(b.canPlayType(d[e])){c=null;break a}c="fmt.noneavailable"}catch(h){c="html5.missingapi"}}c=!c}c&&(c=pf(a)||a.A.assets.js);
a.A.disable.html5=!c;c||(a.A.args.html5_unavailable="1")}b=!!a.A.disable.html5}return b?nf(a)?"flash":"unsupported":"html5"};
tf=function(a,b){if((!b||(5!=(Paa[b.errorCode]||5)?0:-1!=Qaa.indexOf(b.errorCode)))&&nf(a)){var c=rf(a);c&&c.stopVideo&&c.stopVideo();var d=a.A;c&&c.getUpdatedConfigurationData&&(c=c.getUpdatedConfigurationData(),d=g.ee(c));d.args.autoplay=1;d.args.html5_unavailable="1";lf(a,d);sf(a,"flash")}};
sf=function(a,b){a.isDisposed()||(b||(b=qf(a)),("flash"==b?a.xO:"html5"==b?a.yO:a.zO).call(a))};
pf=function(a){var b=!0,c=rf(a);c&&a.A&&(a=a.A,b=g.w(c,"version")==a.assets.js);return b&&!!g.m("yt.player.Application.create")};
rf=function(a){var b=g.x(a.C);!b&&a.R&&a.R.querySelector&&(b=a.R.querySelector("#"+a.C));return b};
uf=function(a,b,c){var d=b[c];return function(){try{return a.Eb=null,d.apply(b,arguments)}catch(e){"Bad NPObject as private data!"!=e.message&&"sendAbandonmentPing"!=c&&(e.message+=" ("+c+")",a.Eb=e,g.Cb(e,"WARNING"))}}};
gf=function(a){a.M=!1;if(a.Xa)for(var b in a.B)a.Xa(b,a.B[b]);for(var c in a.qa)g.Ab((0,window.parseInt)(c,10));a.qa={};a.X=null;a.Xa=null;for(var d in a.api)a.api[d]=null;a.api.addEventListener=(0,g.p)(a.xe,a);a.api.removeEventListener=(0,g.p)(a.DM,a);a.api.destroy=(0,g.p)(a.dispose,a);a.api.getLastError=(0,g.p)(a.Wz,a);a.api.getPlayerType=(0,g.p)(a.kA,a);a.api.getCurrentVideoConfig=(0,g.p)(a.vz,a);a.api.loadNewVideoConfig=(0,g.p)(a.Lo,a);a.api.isReady=(0,g.p)(a.MO,a)};
kf=function(a,b){var c=b;if("string"==typeof b){if(a.bb[b])return a.bb[b];c=function(){var a=g.m(b);a&&a.apply(g.da,arguments)};
a.bb[b]=c}return c?c:null};
Raa=function(a,b){var c="ytPlayer"+b+a.la;a.B[b]=c;g.da[c]=function(c){var e=g.yb(function(){a.isDisposed()||(a.aa.ma(b,c),g.Sa(a.qa,String(e)))},0);
g.Ta(a.qa,String(e),!0)};
return c};
vf=function(a){return(a=rf(a))?"div"==a.tagName.toLowerCase()?"html5":"flash":null};
wf=function(a){g.Bd("dcp");a.cancel();gf(a);a.F=null;a.A&&(a.A.loaded=!1);var b=rf(a);"html5"==vf(a)?a.O=b:b&&b.destroy&&b.destroy();g.Xc(a.D);ff(a.ia);a.G=null;a.Y=null};
g.zf=function(a,b){a=g.la(a)?g.Mc(a):a;b=g.ee(b);var c=g.xf+"_"+g.qa(a),d=g.yf[c];if(d)return d.Lo(b),d.api;d=new jf(a,c);g.yf[c]=d;g.v("player-added",d.api);g.qb(d,g.ra(Saa,d));g.yb(function(){d.Lo(b)},0);
return d.api};
Saa=function(a){g.yf[a.getId()]=null};
g.Af=function(a){a=g.x(a);if(!a)return null;var b=g.xf+"_"+g.qa(a),c=g.yf[b];c||(c=new jf(a,b),g.yf[b]=c);return c.api};
g.Bf=function(){return g.A(g.x("page-container"),"remote-connected")};
Taa=function(){g.l("yt.abuse.botguardInitialized",ge,void 0);g.l("yt.abuse.invokeBotguard",g.he,void 0);g.l("yt.abuse.dclkstatus.checkDclkStatus",ie,void 0);g.l("yt.player.exports.navigate",g.ve,void 0);g.l("yt.player.embed",g.zf,void 0);g.l("yt.player.getPlayerByElement",g.Af,void 0);g.l("yt.util.activity.init",g.be,void 0);g.l("yt.util.activity.getTimeSinceActive",g.ce,void 0);g.l("yt.util.activity.setTimestamp",ae,void 0);var a=g.m("ytplayer.config");Cf(a);g.m("ytspf.enabled")&&(Df=g.zb(Ef,5E3),
(a=g.Ff())?(a.addEventListener("onReady",Ef),a.addEventListener("onStateChange",Ef)):Gf("unable to init PP monitor"))};
Cf=function(a){for(var b in g.yf){var c=g.yf[b];c&&c.cancel()}if(a=a||null){b=g.Ff();var d=!0,c=g.Hf;g.Hf=null;b&&b.getVideoData&&c&&(d=b.getVideoData(),d=!!c.fullscreen||d.video_id!=a.args.video_id||d.list!=a.args.list||d.video_id!=c.videoId||d.list!=c.listId);d?(If="",g.zf("player-api",a)):b.playVideo();a=g.ee(a);a.loaded=!0}Ef();g.l("ytplayer.config",a,void 0)};
g.Ff=function(){var a=g.m("yt.player.getPlayerByElement");return a?a("player-api"):null};
Ef=function(){var a=g.Ff();if(a){var b;b=g.x("player");b=!b||g.A(b,"off-screen");var c=1==(a&&a.isReady()?a.getPlayerState():void 0),d="watch"==g.t("PAGE_NAME"),e=g.Bf();!c||d||e||(Gf("PP playing off watch (paused)"),a.pauseVideo());b&&d?Gf("PP off-screen on watch"):b||d||Gf("PP !off-screen off watch")}};
Gf=function(a){var b=g.t("PAGE_NAME");b&&(b=[b,If,g.m("_spf_state.nav-counter")],a+="("+b.join(",")+")",g.l("yt.www.persistentplayer.issue",a,void 0),g.Cb(Error(a),"WARNING"))};
Kf=function(){g.Bd("ol");g.t("CSI_TICK_PAINT_TIME")?window.requestAnimationFrame&&!window.document.hidden?window.requestAnimationFrame(function(){(0,window.setTimeout)(function(){g.Bd("cpt");Jf()},0)}):window.document.hidden?(g.Bd("cpt"),Jf()):(0,window.setTimeout)(function(){g.Bd("cpt");
Jf()},0):Jf()};
Jf=function(){Lf("init");var a=g.t("PAGE_NAME",void 0);a&&Lf("init-"+a)};
Lf=function(a){g.Ob()?Mf.push(g.Pb(g.ra(g.Nb,a),0)):g.v(a)};
Nf=function(){g.Sb(Mf);Mf.length=0;var a=g.t("PAGE_NAME",void 0);a&&g.Nb("dispose-"+a);g.Nb("dispose")};
Uaa=function(){Kf()};
Vaa=function(){g.t("TIMING_REPORT_ON_UNLOAD")&&Ad(!0);Od("u");Md("u");Nf();g.Nb("pageunload")};
Waa=function(a,b,c,d,e){for(var h=window.document.getElementsByTagName("script"),k=!1,n=0,r=h.length;n<r;n++)if(0<h[n].src.indexOf("/debug-")){k=!0;break}k&&(e||(e=Error(),e.message=a,e.fileName=b,e.lineNumber=c,(0,window.isNaN)(d)||(e.columnNumber=d)),g.Cb(e))};
Sf=function(){Of=1;Pf=Qf=0;g.t("TIMING_REPORT_ON_UNLOAD")&&Ad(!0);Od("n");Md("n");Fd();Dd("n");zd("mark_navigation_requested");Rf(Xaa);g.Nb("navigate")};
Wf=function(a){a=a.detail.part||a.detail.partial;g.Bd("nc"+Qf);++Qf;if(!a.data||!a.data.deferDispose){var b=1==Of;Of=2;b?(Rf(Yaa),Tf()):Rf(Zaa);if(b=a.data&&a.data.swfcfg)Uf(a.timing,b.args),Vf(b)}};
Xf=function(){g.Bd("np"+Pf);++Pf};
Yf=function(a){a=a.detail.response;var b=1==Of;Of=3;b&&(Rf($aa),Tf());if(b=a.data&&a.data.swfcfg)Uf(a.timing,b.args),Vf(b)};
ag=function(a){g.Bd("nd");a=a.detail.response;g.Zf=a.cacheKey;a=a.timing;var b=window._spf_state,b=b&&b["nav-counter"]||0;Cd(void 0).yt_nav=b;Dd("ne",a.responseStart);b=Math.max(0,a.responseStart-a.navigationStart);Cd(void 0).srt=b;var c=(b=!!a.spfCached)?"hot":"warm";Cd(void 0).yt_lt=c;var c=!!a.spfPrefetched,d=+c;Cd(void 0).yt_pft=d;g.Bd("pfs",a.fetchStart);var d=a.responseStart,e=Hd(void 0).span,h=xd(void 0);"pfs"in h&&(e.preq=(d||(0,g.yd)())-h.pfs);"redirectStart"in a&&Id(a);Rf($f);window.document.getElementById("content").style.height=
"";g.t("EXP_LACT_HISTORY")&&b&&!c&&ae();Kf();Of=0};
bg=function(a){var b=a.detail.url;if(a=a.detail.err)a.message&&(a.message+=" (url: "+b+")"),g.Cb(a)};
cg=function(a){g.Rd(g.nd({spfreload:"1",url:a.detail.url,reason:a.detail.reason}))};
bba=function(){aba()};
cba=function(){};
Tf=function(){var a=window.document.getElementById("content");-1<a.className.indexOf("spf-animate")&&(a.style.height=a.clientHeight+"px");Nf();var a=g.t("TIMING_ACTION"),b;for(b in g.vb)delete g.vb[b];g.wb("PREVIOUS_ACTION",a);g.l("ytplayer.config",null,void 0);if((b=g.Ff())&&b.stopVideo){if(b.stopVideo(),b=b.getLastError())If=b,(b=g.x("movie_player"))&&b.stopVideo?(b.stopVideo(),If="recovered"):If="missing2"}else If="missing";Ef()};
Vf=function(a){"cfg"in xd(void 0)||g.Bd("cfg");Cf(a)};
Rf=function(a){var b=window.document.getElementById("progress");b||(b=window.document.createElement("div"),b.id="progress",b.appendChild(window.document.createElement("dt")),b.appendChild(window.document.createElement("dd")),window.document.body.appendChild(b));g.Rb(dg);dg=g.Qb(function(){var c=a[0],d=a[1],e=a[2];b.className="";var h=b.style;h.transitionDuration=h.webkitTransitionDuration=c+"ms";h.width=d+"%";g.Ab(eg);eg=g.yb(function(){b.className=e},c)},0)};
aba=function(){var a=$f[0]+50;g.Ab(eg);eg=g.yb(function(){var a=window.document.getElementById("progress");a&&a.parentNode.removeChild(a)},a)};
Uf=function(a,b){var c=a&&a.spfCached,d=a&&a.spfPrefetched,e=[];c&&!d&&(0,g.u)(dba,function(a){a in b&&(delete b[a],e.push(a))});
g.t("EXP_DEBUG_PREFETCH")&&(e.sort(),c={a:"removeNonCacheableVideoVars",cached:c,prefetched:d,deleted:e.join("")},g.Rd(g.nd(c)))};
fg=function(){g.Tb.call(this,"www/base");this.B=0};
gg=function(a){(a=a.detail.name)&&Wb(a)};
g.aa=[];g.hg=g.hg||{};g.da=this;pa="closure_uid_"+(1E9*Math.random()>>>0);aaa=0;g.yd=Date.now||function(){return+new Date};g.sa[" "]=g.ea;var eaa,faa,gaa,haa,iaa,jaa,daa;g.za=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
eaa=/&/g;faa=/</g;gaa=/>/g;haa=/"/g;iaa=/'/g;jaa=/\x00/g;daa=/[\x00&<>"']/;g.ig=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};
g.eba=2147483648*Math.random()|0;g.Ha=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;
if(g.la(a))return g.la(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
g.fba=Array.prototype.lastIndexOf?function(a,b,c){return Array.prototype.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;
0>c&&(c=Math.max(0,a.length+c));if(g.la(a))return g.la(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};
g.u=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=g.la(a)?a.split(""):a,h=0;h<d;h++)h in e&&b.call(c,e[h],h,a)};
g.Td=Array.prototype.filter?function(a,b,c){return Array.prototype.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],h=0,k=g.la(a)?a.split(""):a,n=0;n<d;n++)if(n in k){var r=k[n];
b.call(c,r,n,a)&&(e[h++]=r)}return e};
g.jg=Array.prototype.map?function(a,b,c){return Array.prototype.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),h=g.la(a)?a.split(""):a,k=0;k<d;k++)k in h&&(e[k]=b.call(c,h[k],k,a));
return e};
g.kg=Array.prototype.reduce?function(a,b,c,d){d&&(b=(0,g.p)(b,d));return Array.prototype.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;
(0,g.u)(a,function(c,k){e=b.call(d,e,c,k,a)});
return e};
g.lg=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=g.la(a)?a.split(""):a,h=0;h<d;h++)if(h in e&&b.call(c,e[h],h,a))return!0;
return!1};
g.mg=Array.prototype.every?function(a,b,c){return Array.prototype.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=g.la(a)?a.split(""):a,h=0;h<d;h++)if(h in e&&!b.call(c,e[h],h,a))return!1;
return!0};g.ng=g.Na(!1);g.og=g.Na(!0);g.pg=g.Na(null);var Va="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");a:{var qg=g.da.navigator;if(qg){var rg=qg.userAgent;if(rg){g.Xa=rg;break a}}g.Xa=""};var ob;g.cb.prototype.get=function(){var a;0<this.C?(this.C--,a=this.A,this.A=a.next,a.next=null):a=this.B();return a};var kb=new g.cb(function(){return new fb},function(a){a.reset()},100);
eb.prototype.remove=function(){var a=null;this.A&&(a=this.A,this.A=this.A.next,this.A||(this.C=null),a.next=null);return a};
fb.prototype.set=function(a,b){this.Ee=a;this.scope=b;this.next=null};
fb.prototype.reset=function(){this.next=this.scope=this.Ee=null};var gb,ib=!1,jb=new eb;g.pb.prototype.Gd=!1;g.pb.prototype.isDisposed=function(){return this.Gd};
g.pb.prototype.dispose=function(){this.Gd||(this.Gd=!0,this.W())};
g.pb.prototype.W=function(){if(this.Ib)for(;this.Ib.length;)this.Ib.shift()()};g.q(g.tb,g.pb);g.f=g.tb.prototype;g.f.subscribe=function(a,b,c){var d=this.Ed[a];d||(d=this.Ed[a]=[]);var e=this.D;this.A[e]=a;this.A[e+1]=b;this.A[e+2]=c;this.D=e+3;d.push(e);return e};
g.f.unsubscribe=function(a,b,c){if(a=this.Ed[a]){var d=this.A;if(a=g.Ga(a,function(a){return d[a+1]==b&&d[a+2]==c}))return this.Fd(a)}return!1};
g.f.Fd=function(a){var b=this.A[a];if(b){var c=this.Ed[b];0!=this.B?(this.C.push(a),this.A[a+1]=g.ea):(c&&g.La(c,a),delete this.A[a],delete this.A[a+1],delete this.A[a+2])}return!!b};
g.f.ma=function(a,b){var c=this.Ed[a];if(c){for(var d=Array(arguments.length-1),e=1,h=arguments.length;e<h;e++)d[e-1]=arguments[e];if(this.F)for(e=0;e<c.length;e++){var k=c[e];maa(this.A[k+1],this.A[k+2],d)}else{this.B++;try{for(e=0,h=c.length;e<h;e++)k=c[e],this.A[k+1].apply(this.A[k+2],d)}finally{if(this.B--,0<this.C.length&&0==this.B)for(;c=this.C.pop();)this.Fd(c)}}return 0!=e}return!1};
g.f.clear=function(a){if(a){var b=this.Ed[a];b&&((0,g.u)(b,this.Fd,this),delete this.Ed[a])}else this.A.length=0,this.Ed={}};
g.f.sb=g.ba(1);g.f.W=function(){g.tb.N.W.call(this);this.clear();this.C.length=0};g.vb=window.yt&&window.yt.config_||window.ytcfg&&window.ytcfg.data_||{};g.l("yt.config_",g.vb,void 0);g.l("yt.tokens_",window.yt&&window.yt.tokens_||{},void 0);g.Db=window.yt&&window.yt.msgs_||g.m("window.ytcfg.msgs")||{};g.l("yt.msgs_",g.Db,void 0);g.Se="Microsoft Internet Explorer"==window.navigator.appName;var gba=g.m("yt.pubsub.instance_")||new g.tb;g.tb.prototype.subscribe=g.tb.prototype.subscribe;g.tb.prototype.unsubscribeByKey=g.tb.prototype.Fd;g.tb.prototype.publish=g.tb.prototype.ma;g.tb.prototype.clear=g.tb.prototype.clear;g.l("yt.pubsub.instance_",gba,void 0);var Ib=g.m("yt.pubsub.subscribedKeys_")||{};g.l("yt.pubsub.subscribedKeys_",Ib,void 0);var Kb=g.m("yt.pubsub.topicToKeys_")||{};g.l("yt.pubsub.topicToKeys_",Kb,void 0);var Jb=g.m("yt.pubsub.isSynchronous_")||{};
g.l("yt.pubsub.isSynchronous_",Jb,void 0);var Hb=g.m("yt.pubsub.skipSubId_")||null;g.l("yt.pubsub.skipSubId_",Hb,void 0);g.f=g.Tb.prototype;g.f.RM=function(){this.bk()||this.init()};
g.f.enable=function(){this.A=1;(0,g.u)("string"==typeof this.page?[this.page]:this.page,function(a){a&&(this.subscribe("init-"+a,this.RM,this),this.subscribe("dispose-"+a,this.dispose,this),g.t("PAGE_NAME")==a&&g.Ub(this))},this)};
g.f.init=function(){g.Rb(this.C);this.A=2;this.G&&this.G()};
g.f.bk=function(){return 2==this.A};
g.f.dispose=function(){this.A=3;g.Rb(this.C);this.F&&this.F()};
g.f.disable=function(){this.A=4;this.clear();try{this.dispose()}catch(a){g.Cb(a)}};
g.f.subscribe=function(a,b,c){a=g.Lb(a,b,c);this.D.push(a);return a};
g.f.clear=function(){g.Mb(this.D);this.D=[]};var Vb=g.m("yt.modules.registry_")||{};g.l("yt.modules.registry_",Vb,void 0);var saa={area:!0,base:!0,br:!0,col:!0,command:!0,embed:!0,hr:!0,img:!0,input:!0,keygen:!0,link:!0,meta:!0,param:!0,source:!0,track:!0,wbr:!0};g.hba=RegExp("[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]");g.iba=RegExp("^[^\u0591-\u06ef\u06fa-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]*[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]");g.sg=RegExp("^[^A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]*[\u0591-\u06ef\u06fa-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]");g.Zb.prototype.Yf=!0;g.Zb.prototype.$e=function(){return this.A};
g.Zb.prototype.toString=function(){return"Const{"+this.A+"}"};
var Yb={};bc.prototype.Yf=!0;var ac={};bc.prototype.$e=function(){return this.A};
var oaa=dc(""),naa=/^([-,."'%_!# a-zA-Z0-9]+|(?:rgb|hsl)a?\([0-9.%, ]+\))$/;g.gc.prototype.Yf=!0;g.gc.prototype.$e=function(){return this.A};
g.gc.prototype.Nm=!0;g.gc.prototype.Gg=function(){return 1};
var paa=/^(?:(?:https?|mailto|ftp):|[^&:/?#]*(?:[/?#]|$))/i,fc={};g.ic("about:blank");g.lc.prototype.Yf=!0;g.lc.prototype.$e=function(){return this.A};
g.lc.prototype.Nm=!0;g.lc.prototype.Gg=function(){return 1};
var kc={};var sc,raa,qaa,nc;g.oc.prototype.Nm=!0;g.oc.prototype.Gg=function(){return this.C};
g.oc.prototype.Yf=!0;g.oc.prototype.$e=function(){return this.A};
sc=/^[a-zA-Z0-9-]+$/;raa={action:!0,cite:!0,data:!0,formaction:!0,href:!0,manifest:!0,poster:!0,src:!0};qaa={APPLET:!0,BASE:!0,EMBED:!0,IFRAME:!0,LINK:!0,MATH:!0,META:!0,OBJECT:!0,SCRIPT:!0,STYLE:!0,SVG:!0,TEMPLATE:!0};nc={};g.jba=g.qc("<!DOCTYPE html>",0);g.tg=g.qc("",0);g.ug=g.qc("<br>",0);var Ac={};var taa=/\.vflset|-vfl[a-zA-Z0-9_+=-]+/,uaa=/-[a-zA-Z]{2,3}_[a-zA-Z]{2,3}(?=(\/|$))/;g.kba=Math.sign||function(a){return 0<a?1:0>a?-1:a};g.f=g.Ec.prototype;g.f.clone=function(){return new g.Ec(this.x,this.y)};
g.f.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};
g.f.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};
g.f.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};
g.f.scale=function(a,b){var c=g.ma(b)?b:a;this.x*=a;this.y*=c;return this};var xg,yg,Hc,Cg;g.xe=Za();g.z=g.Ya("Trident")||g.Ya("MSIE");g.vg=g.Ya("Edge");g.wg=g.vg||g.z;g.we=g.Ya("Gecko")&&!(g.xa(g.Xa.toLowerCase(),"webkit")&&!g.Ya("Edge"))&&!(g.Ya("Trident")||g.Ya("MSIE"))&&!g.Ya("Edge");g.Sc=g.xa(g.Xa.toLowerCase(),"webkit")&&!g.Ya("Edge");g.Sc&&g.Ya("Mobile");g.Xe=g.Ya("Macintosh");g.We=g.Ya("Windows");g.lba=g.Ya("Linux")||g.Ya("CrOS");xg=g.da.navigator||null;xg&&g.xa(xg.appVersion||"","X11");g.mba=g.Ya("Android");g.nba=g.Fc();g.oba=g.Ya("iPad");
a:{var zg="",Ag=function(){var a=g.Xa;if(g.we)return/rv\:([^\);]+)(\)|;)/.exec(a);if(g.vg)return/Edge\/([\d\.]+)/.exec(a);if(g.z)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(g.Sc)return/WebKit\/(\S+)/.exec(a);if(g.xe)return/(?:Version)[ \/]?(\S+)/.exec(a)}();
Ag&&(zg=Ag?Ag[1]:"");if(g.z){var Bg=Gc();if(null!=Bg&&Bg>(0,window.parseFloat)(zg)){yg=String(Bg);break a}}yg=zg}g.Ic=yg;Hc={};Cg=g.da.document;g.Kc=Cg&&g.z?Gc()||("CSS1Compat"==Cg.compatMode?(0,window.parseInt)(g.Ic,10):5):void 0;var vaa;vaa=!g.z||g.Lc(9);g.pba=!g.we&&!g.z||g.z&&g.Lc(9)||g.we&&g.Jc("1.9.1");g.Dg=g.z&&!g.Jc("9");g.qba=g.z||g.xe||g.Sc;g.rba=g.z&&!g.Lc(9);var Oc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};g.Eg="StopIteration"in g.da?g.da.StopIteration:{message:"StopIteration",stack:""};g.ed=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;g.hf=g.Ya("Firefox");g.Fg=g.Fc()||g.Ya("iPod");g.Gg=g.Ya("iPad");g.sba=g.Ya("Android")&&!($a()||g.Ya("Firefox")||Za()||g.Ya("Silk"));g.Hg=$a();g.Ig=g.Ya("Safari")&&!($a()||g.Ya("Coast")||Za()||g.Ya("Edge")||g.Ya("Silk")||g.Ya("Android"))&&!(g.Fc()||g.Ya("iPad")||g.Ya("iPod"));var rd={},Aaa=0,tba=g.m("yt.net.ping.workerUrl_")||null;g.l("yt.net.ping.workerUrl_",tba,void 0);g.sd.prototype.Xb=g.ba(2);g.td.prototype.toString=function(){return this.topic};var uba=g.m("yt.pubsub2.instance_")||new g.tb;g.tb.prototype.subscribe=g.tb.prototype.subscribe;g.tb.prototype.unsubscribeByKey=g.tb.prototype.Fd;g.tb.prototype.publish=g.tb.prototype.ma;g.tb.prototype.clear=g.tb.prototype.clear;g.l("yt.pubsub2.instance_",uba,void 0);g.Jg=g.m("yt.pubsub2.subscribedKeys_")||{};g.l("yt.pubsub2.subscribedKeys_",g.Jg,void 0);g.Kg=g.m("yt.pubsub2.topicToKeys_")||{};g.l("yt.pubsub2.topicToKeys_",g.Kg,void 0);g.Lg=g.m("yt.pubsub2.isAsync_")||{};
g.l("yt.pubsub2.isAsync_",g.Lg,void 0);g.l("yt.pubsub2.skipSubKey_",null,void 0);g.q(wd,g.sd);var Daa=new g.td("timing-sent",wd);var Jd=window.performance||window.mozPerformance||window.msPerformance||window.webkitPerformance||{},Baa=(0,g.p)(Jd.clearResourceTimings||Jd.webkitClearResourceTimings||Jd.mozClearResourceTimings||Jd.msClearResourceTimings||Jd.oClearResourceTimings||g.ea,Jd),zd=Jd.mark?function(a){Jd.mark(a)}:g.ea;g.vba=g.Sc?"webkit":g.we?"moz":g.z?"ms":g.xe?"o":"";g.Mg=g.m("yt.dom.getNextId_");if(!g.Mg){g.Mg=function(){return++wba};
g.l("yt.dom.getNextId_",g.Mg,void 0);var wba=0};g.Wd.prototype.preventDefault=function(){this.event&&(this.event.returnValue=!1,this.event.preventDefault&&this.event.preventDefault())};
g.Wd.prototype.stopPropagation=function(){this.event&&(this.event.cancelBubble=!0,this.event.stopPropagation&&this.event.stopPropagation())};
g.Wd.prototype.stopImmediatePropagation=function(){this.event&&(this.event.cancelBubble=!0,this.event.stopImmediatePropagation&&this.event.stopImmediatePropagation())};
var Faa={stopImmediatePropagation:1,stopPropagation:1,preventMouseEvent:1,preventManipulation:1,preventDefault:1,layerX:1,layerY:1,scale:1,rotation:1,webkitMovementX:1,webkitMovementY:1};g.Xd=g.m("yt.events.listeners_")||{};g.l("yt.events.listeners_",g.Xd,void 0);var Zd=g.m("yt.events.counter_")||{count:0};g.l("yt.events.counter_",Zd,void 0);var Gaa={enablejsapi:1},Haa={},Iaa={allowscriptaccess:"always",allowfullscreen:"true",bgcolor:"#000000"};de.prototype.clone=function(){var a=new de,b;for(b in this)if(this.hasOwnProperty(b)){var c=this[b];"object"==g.ga(c)?a[b]=g.Ua(c):a[b]=c}return a};g.fe=null;g.le=/\s*;\s*/;g.f=g.ke.prototype;g.f.isEnabled=function(){return window.navigator.cookieEnabled};
g.f.set=function(a,b,c,d,e,h){if(/[;=\s]/.test(a))throw Error('Invalid cookie name "'+a+'"');if(/[;\r\n]/.test(b))throw Error('Invalid cookie value "'+b+'"');g.ca(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";h=h?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,g.yd)()+1E3*c)).toUTCString();this.A.cookie=a+"="+b+e+d+c+h};
g.f.get=function(a,b){for(var c=a+"=",d=(this.A.cookie||"").split(g.le),e=0,h;h=d[e];e++){if(0==h.lastIndexOf(c,0))return h.substr(c.length);if(h==a)return""}return b};
g.f.remove=function(a,b,c){var d=g.ca(this.get(a));this.set(a,"",0,b,c);return d};
g.f.Rb=g.ba(3);g.f.pb=g.ba(4);g.f.isEmpty=function(){return!this.A.cookie};
g.f.sb=g.ba(0);g.f.De=g.ba(5);g.f.clear=function(){for(var a=g.me(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};
g.ne=new g.ke(window.document);g.ne.C=3950;g.f=g.Ae.prototype;g.f.getHeight=function(){return this.bottom-this.top};
g.f.clone=function(){return new g.Ae(this.top,this.right,this.bottom,this.left)};
g.f.contains=function(a){return g.Be(this,a)};
g.f.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};
g.f.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};
g.f.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};
g.f.scale=function(a,b){var c=g.ma(b)?b:a;this.left*=a;this.right*=a;this.top*=c;this.bottom*=c;return this};var Ce;Ce={};g.Ng=g.we?"MozUserSelect":g.Sc||g.vg?"WebkitUserSelect":null;g.fa(g.Ke);g.Je=g.m("yt.prefs.UserPrefs.prefs_")||{};g.l("yt.prefs.UserPrefs.prefs_",g.Je,void 0);g.f=g.Ke.prototype;g.f.get=function(a,b){Me(a);Le(a);var c=void 0!==g.Je[a]?g.Je[a].toString():null;return null!=c?c:b?b:""};
g.f.set=function(a,b){Me(a);Le(a);if(null==b)throw"ExpectedNotNull";g.Je[a]=b.toString()};
g.f.remove=function(a){Me(a);Le(a);delete g.Je[a]};
g.f.save=function(){var a;a=[];for(var b in g.Je)a.push(b+"="+(0,window.escape)(g.Je[b]));a=a.join("&");g.oe("PREF",a,63072E3)};
g.f.clear=function(){g.Je={}};g.Og=g.Oa(function(){if(g.z)return g.Jc("10.0");var a=window.document.createElement("DIV"),b=g.ze(),c={transition:"opacity 1s linear"};b&&(c[b+"-transition"]="opacity 1s linear");g.wc(a,g.uc("div",{style:c}));return""!=g.Ee(a.firstChild,"transition")});g.fa(g.Te);g.Te.prototype.getVersion=function(){return[this.major,this.minor,this.A]};var Maa=/cssbin\/(?:debug-)?([a-zA-Z0-9_-]+?)(?:-2x|-web|-rtl|-vfl|.css)/;var of;var Pg=g.Xa,Pg=Pg.toLowerCase();if(g.xa(Pg,"android")){var Qg=Pg.match(/android\D*(\d\.\d)[^\;|\)]*[\;\)]/);if(Qg)of=Number(Qg[1]);else{var Rg={cupcake:1.5,donut:1.6,eclair:2,froyo:2.2,gingerbread:2.3,honeycomb:3,"ice cream sandwich":4,jellybean:4.1},Sg=Pg.match("("+g.Qa(Rg).join("|")+")");of=Sg?Rg[Sg[0]]:0}}else of=void 0;var Naa=['video/mp4; codecs="avc1.42001E, mp4a.40.2"','video/webm; codecs="vp8.0, vorbis"'],Oaa=['audio/mp4; codecs="mp4a.40.2"'];g.q(g.df,g.pb);g.df.prototype.Wa=g.ba(6);g.df.prototype.W=function(){ff(this);g.df.N.W.call(this)};var Paa={"api.invalidparam":2,auth:150,"drm.auth":150,heartbeat:150,"html5.unsupportedads":5,"fmt.noneavailable":5,"fmt.decode":5,"fmt.unplayable":5,"html5.missingapi":5,"drm.unavailable":5};g.q(jf,g.pb);var Qaa=["drm.unavailable","fmt.noneavailable","html5.missingapi","html5.unsupportedads","html5.unsupportedlive"];g.f=jf.prototype;g.f.getId=function(){return this.la};
g.f.Lo=function(a,b){this.isDisposed()||(lf(this,a),b||qf(this),sf(this,b),this.M&&mf(this))};
g.f.vz=function(){return this.tb};
g.f.yO=function(){if(!this.ga){var a=pf(this);a&&"html5"==vf(this)?(this.F="html5",this.M||this.Yg()):(wf(this),this.F="html5",a&&this.O?(this.D.appendChild(this.O),this.Yg()):(this.A.loaded=!0,this.V=(0,g.p)(function(){var a=this.D,c=this.A.clone();g.m("yt.player.Application.create")(a,c);this.Yg()},this),this.ga=!0,a?this.V():(g.Cc(this.A.assets.js,this.V),g.cf(this.A.assets.css))))}};
g.f.xO=function(){var a=this.A.clone();if(!this.G){var b=rf(this);b&&(this.G=window.document.createElement("span"),this.G.tabIndex=0,ef(this.ia,this.G,"focus",this.Lt),this.Y=window.document.createElement("span"),this.Y.tabIndex=0,ef(this.ia,this.Y,"focus",this.Lt),g.Yc(this.G,b),g.$c(this.Y,b))}a.attrs.width=a.attrs.width||"100%";a.attrs.height=a.attrs.height||"100%";"flash"==vf(this)?(this.F="flash",this.M||bf(a,!1,(0,g.p)(this.Yg,this))):(wf(this),this.F="flash",this.A.loaded=!0,g.af(this.D,a),
this.Yg())};
g.f.Lt=function(){rf(this).focus()};
g.f.Yg=function(){if(!this.isDisposed()){var a=rf(this),b=!1;try{a&&a.getApiInterface&&a.getApiInterface()&&(b=!0)}catch(h){}if(b)if(this.ga=!1,a.isNotServable&&a.isNotServable(this.A.args.video_id))tf(this);else{gf(this);this.M=!0;a=rf(this);a.addEventListener&&(this.X=uf(this,a,"addEventListener"));a.removeEventListener&&(this.Xa=uf(this,a,"removeEventListener"));for(var b=a.getApiInterface(),b=b.concat(a.getInternalApiInterface()),c=0;c<b.length;c++){var d=b[c];this.api[d]||(this.api[d]=uf(this,
a,d))}for(var e in this.B)this.X(e,this.B[e]);mf(this);this.ab&&this.ab(this.api);this.aa.ma("onReady",this.api)}else this.Nb=g.yb((0,g.p)(this.Yg,this),50)}};
g.f.MO=function(){return this.M};
g.f.xe=function(a,b){if(!this.isDisposed()){var c=kf(this,b);if(c){if(!g.Ia(this.mc,a)&&!this.B[a]){var d=Raa(this,a);this.X&&this.X(a,d)}this.aa.subscribe(a,c);"onReady"==a&&this.M&&g.yb(g.ra(c,this.api),0)}}};
g.f.DM=function(a,b){if(!this.isDisposed()){var c=kf(this,b);c&&this.aa.unsubscribe(a,c)}};
g.f.uy=function(a){a=a?yaa:xaa;for(var b=a(window.document.activeElement);b&&(1!=b.nodeType||b==this.G||b==this.Y||(b.focus(),b!=window.document.activeElement));)b=a(b)};
g.f.np=function(a){g.v("a11y-announce",a)};
g.f.EI=function(a){tf(this,a)};
g.f.II=function(a){g.v("WATCH_LATER_VIDEO_ADDED",a)};
g.f.JI=function(a){g.v("WATCH_LATER_VIDEO_REMOVED",a)};
g.f.nI=function(){this.lb||(g.Hg?(this.fb=g.Rc(window.document),ef(this.J,window,"scroll",this.PK),ef(this.J,this.D,"touchmove",this.vK)):(ef(this.J,this.D,"mousewheel",this.Xt),ef(this.J,this.D,"wheel",this.Xt)),this.lb=!0)};
g.f.oI=function(){ff(this.J);this.lb=!1};
g.f.Xt=function(a){g.$d(a)};
g.f.PK=function(){window.scrollTo(this.fb.x,this.fb.y)};
g.f.vK=function(a){a.preventDefault()};
g.f.zO=function(){wf(this);this.F="unsupported";var a='Adobe Flash Player or an HTML5 supported browser is required for video playback. <br> <a href="http://get.adobe.com/flashplayer/">Get the latest Flash Player</a> <br> <a href="/html5">Learn more about upgrading to an HTML5 browser</a>',b=window.navigator.userAgent.match(/Version\/(\d).*Safari/);b&&5<=(0,window.parseInt)(b[1],10)&&(a='Adobe Flash Player or QuickTime is required for video playback. <br> <a href="http://get.adobe.com/flashplayer/"> Get the latest Flash Player</a> <br> <a href="http://www.apple.com/quicktime/download/">Get the latest version of QuickTime</a>');
b=this.A.messages.player_fallback||a;a=g.x("player-unavailable");g.x("unavailable-submessage")&&a&&(g.x("unavailable-submessage").innerHTML=b,(b=g.y("icon",a))&&g.zc(b,"icon")&&(b.src=g.w(b,"icon")),g.Ie(a,!0),g.C(g.x("player"),"off-screen-trigger"))};
g.f.kA=function(){return this.F||vf(this)};
g.f.Wz=function(){return this.Eb};
g.f.cancel=function(){this.V&&g.Dc(this.A.assets.js,this.V);g.Ab(this.Nb);this.ga=!1};
g.f.W=function(){wf(this);if(this.O&&this.A)try{this.O.destroy()}catch(b){g.Cb(b)}this.bb=null;for(var a in this.B)g.da[this.B[a]]=null;this.tb=this.A=this.api=null;delete this.D;delete this.R;jf.N.W.call(this)};g.yf={};g.xf="player_uid_"+(1E9*Math.random()>>>0);var xba=g.m("yt.abuse.botguardInitialized")||ge;g.l("yt.abuse.botguardInitialized",xba,void 0);var yba=g.m("yt.abuse.invokeBotguard")||g.he;g.l("yt.abuse.invokeBotguard",yba,void 0);var zba=g.m("yt.abuse.dclkstatus.checkDclkStatus")||ie;g.l("yt.abuse.dclkstatus.checkDclkStatus",zba,void 0);var Aba=g.m("yt.player.exports.navigate")||g.ve;g.l("yt.player.exports.navigate",Aba,void 0);var Bba=g.m("yt.player.embed")||g.zf;g.l("yt.player.embed",Bba,void 0);var Cba=g.m("yt.player.getPlayerByElement")||g.Af;
g.l("yt.player.getPlayerByElement",Cba,void 0);var Dba=g.m("yt.util.activity.init")||g.be;g.l("yt.util.activity.init",Dba,void 0);var Eba=g.m("yt.util.activity.getTimeSinceActive")||g.ce;g.l("yt.util.activity.getTimeSinceActive",Eba,void 0);var Fba=g.m("yt.util.activity.setTimestamp")||ae;g.l("yt.util.activity.setTimestamp",Fba,void 0);var Df,If;g.Hf=null;If="";var Mf=[];var Of,eg,dg,Qf,Pf,dba,Xaa,$aa,Yaa,Zaa,$f;Qf=0;Pf=0;dba=["server_prefetched_vast","vmap"];Xaa=[900,60,"waiting"];$aa=[500,99,"waiting"];Yaa=[300,60,"waiting"];Zaa=[400,99,"waiting"];$f=[300,101,"done"];window.yt=window.yt||{};g.l("yt.setConfig",g.wb,void 0);g.l("yt.getConfig",g.t,void 0);g.l("yt.hasMsg",g.Eb,void 0);g.l("yt.pubsub.publish",g.v,void 0);g.l("yt.pubsub.subscribe",g.Lb,void 0);g.l("yt.setMsg",function(a){ub(g.Db,arguments)},void 0);
g.l("yt.setGoogMsg",function(a){ub(g.Db,arguments)},void 0);
g.l("yt.timing.reportAdToVideo",function(a,b,c){c={v:2,s:"youtube",action:c?"watch,ad2video_html5":"watch,ad2video"};a.aft=a.pbs=a.astv||a.actv;var d=[],e;for(e in a)"_"!=e.charAt(0)&&d.push(e+"."+a[e]);c.rt=d.join(",");for(var h in b)"_"!=h.charAt(0)&&(c[h]=b[h]);a=g.t("TIMING_INFO",{});"e"in a&&(c.e=a.e);"ei"in a&&(c.ei=a.ei);Ld(c)},void 0);
g.l("ytcsi.tick",g.Bd,void 0);g.q(fg,g.Tb);
fg.prototype.enable=function(){window.onload=Uaa;window.onunload=Vaa;window.onerror=Waa;var a=window.ytspf||{};a.enabled?(window.addEventListener&&(window.addEventListener("spfrequest",Sf),window.addEventListener("spfpartprocess",Wf),window.addEventListener("spfpartdone",Xf),window.addEventListener("spfprocess",Yf),window.addEventListener("spfdone",ag),window.addEventListener("spferror",bg),window.addEventListener("spfreload",cg),window.addEventListener("spfjsbeforeunload",gg)),a.config=a.config||
{},window.ytdepmap?window.spf.script.ready("spf",function(){a.enabled=window.spf.init(a.config)}):a.enabled=window.spf.init(a.config),this.subscribe("init",bba),this.subscribe("dispose",cba)):window.spf.dispose();
this.subscribe("init",this.init,this);this.subscribe("dispose",this.dispose,this)};
fg.prototype.init=function(){fg.N.init.call(this);(window.ytspf||{}).enabled||window.spf.dispose();var a=window.ytPageFrameLoaded||!1,b,c;!a&&g.t("PAGEFRAME_JS")?(b=g.t("PAGEFRAME_JS",void 0),c=function(){window.ytPageFrameLoaded=!0;g.m("ytbin.www.pageframe.setup")()}):a&&(a=g.m("yt.www.masthead.loadSearchbox"))&&a();
var a=g.t("JS_COMMON_MODULE"),d=g.t("JS_PAGE_MODULES");d||(d=[a]);a=g.t("JS_DELAY_LOAD",0);0<a?(g.Ab(this.B),this.B=g.yb(function(){b&&g.Cc(b,c);window.spf.script.require(d)},a)):(b&&g.Cc(b,c),window.spf.script.require(d));
Taa();g.l("yt.timing.ready_",!0,void 0);Ad(!1);var a=!!g.m("yt.reactLoaded"),e=g.t("REACT_JS",void 0);!a&&e&&g.Cc(e,function(){g.l("yt.reactLoaded",!0,void 0)})};
fg.prototype.dispose=function(){g.Ab(this.B);var a=g.m("ytbin.www.pageframe.cancelSetup");a&&a();g.Bb(Df);if(a=g.Ff())a.removeEventListener("onReady",Ef),a.removeEventListener("onStateChange",Ef);g.l("yt.timing.ready_",!1,void 0);fg.N.dispose.call(this)};
fg.prototype.disable=function(){fg.N.disable.call(this);window.removeEventListener&&(window.removeEventListener("spfrequest",Sf),window.removeEventListener("spfpartprocess",Wf),window.removeEventListener("spfpartdone",Xf),window.removeEventListener("spfprocess",Yf),window.removeEventListener("spfdone",ag),window.removeEventListener("spferror",bg),window.removeEventListener("spfreload",cg),window.removeEventListener("spfjsbeforeunload",gg));window.onload=null;window.onunload=null;window.onerror=null};
g.Xb(new fg);})(_yt_www);
